;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_bg
	.import		_pal_spr
	.import		_ppu_wait_nmi
	.import		_ppu_off
	.import		_ppu_on_all
	.import		_oam_clear
	.import		_oam_meta_spr
	.import		_pad_poll
	.import		_bank_spr
	.import		_bank_bg
	.import		_memcpy
	.import		_set_vram_buffer
	.import		_clear_vram_buffer
	.import		_get_pad_new
	.import		_set_scroll_x
	.import		_get_ppu_addr
	.import		_set_data_pointer
	.import		_set_mt_pointer
	.import		_buffer_4_mt
	.import		_flush_vram_update2
	.export		_bankLevel
	.export		_bankBuffer
	.export		_banked_call
	.export		_bank_push
	.export		_bank_pop
	.import		_set_prg_bank
	.import		_get_prg_bank
	.import		_set_mirroring
	.export		_direction
	.export		_direction_y
	.export		_arg1
	.export		_arg2
	.export		_pad1
	.export		_pad1_new
	.export		_char_state
	.export		_song
	.export		_sound
	.export		_temp_x
	.export		_temp_y
	.export		_temp_sprite
	.export		_old_x
	.export		_old_y
	.export		_eject_L
	.export		_eject_R
	.export		_eject_D
	.export		_eject_U
	.export		_collision_L
	.export		_collision_R
	.export		_collision_U
	.export		_collision_D
	.export		_coordinates
	.export		_location_with_scroll
	.export		_collision
	.export		_map_loaded
	.export		_scrolling_direction
	.export		_metatile_colision_map
	.export		_nametable_to_load
	.export		_offset
	.export		_address
	.export		_x
	.export		_y
	.export		_nt
	.export		_index
	.export		_map
	.export		_scroll_x
	.export		_max_rooms
	.export		_max_scroll
	.export		_room_to_load
	.export		_temp_room
	.export		_current_stage
	.export		_current_level
	.export		_scroll_count
	.export		_pseudo_scroll_x
	.export		_c_map
	.export		_c_map2
	.export		_temp1
	.export		_temp2
	.export		_temp3
	.export		_l_scroll_frames
	.export		_r_scroll_frames
	.export		_Player1
	.export		_Generic
	.export		_Generic2
	.export		_wram_array
	.export		_noah_box
	.export		_topleft
	.export		_bottomleft
	.export		_bg_collision_sub
	.export		_bg_collision_fast
	.export		_bg_coll_L
	.export		_bg_coll_R
	.export		_bg_coll_ladder
	.export		_bg_coll_ladder_top_at_player
	.export		_bg_coll_ladder_top_under_player
	.export		_bg_coll_U
	.export		_bg_coll_D
	.export		_move_player
	.export		_check_player_colision
	.export		_bank0_player_movement
	.export		_bank0_draw_player_sprite
	.export		_function_bank1
	.export		_stage1_level0_0
	.export		_stage1_level0_1
	.export		_stage1_level0_2
	.export		_stage1_level0_3
	.export		_stage1_level0_4
	.export		_stage1_level0_5
	.export		_stage1_level0_6
	.export		_stage1_level0_7
	.export		_stage2_level0_0
	.export		_stage2_level0_1
	.export		_function_bank2
	.export		_stage0_levels
	.export		_stage1_levels
	.export		_stage_table
	.export		_levels_per_stage
	.export		_metatile
	.export		_drawMetatileBlock
	.export		_draw_screen
	.export		_new_cmap
	.export		_prep_scroll_screen
	.export		_handle_scrolling
	.export		_bank2_load_room
	.export		_bank2_scroll_screen
	.export		_function_bank3
	.export		_function_bank4
	.export		_function_bank5
	.export		_function_bank6
	.export		_palette_bg
	.export		_palette_sp
	.export		_main

.segment	"DATA"

_room_to_load:
	.byte	$00
_current_stage:
	.byte	$00
_current_level:
	.byte	$00
_Player1:
	.word	$4000
	.word	$9400
	.res	6,$00
_stage0_levels:
	.addr	_stage1_level0_0
	.addr	_stage1_level0_1
	.addr	_stage1_level0_2
	.addr	_stage1_level0_3
	.addr	_stage1_level0_4
	.addr	_stage1_level0_5
	.addr	_stage1_level0_6
	.addr	_stage1_level0_7
_stage1_levels:
	.addr	_stage2_level0_0
	.addr	_stage2_level0_1
_stage_table:
	.addr	_stage0_levels
	.addr	_stage1_levels

.segment	"RODATA"

_metatile_colision_map:
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$00
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
.segment	"BANK0"
_noah_box:
	.byte	$00
	.byte	$00
	.byte	$4F
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$4F
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$3F
	.byte	$80
	.byte	$06
	.byte	$00
	.byte	$4F
	.byte	$00
	.byte	$06
	.byte	$08
	.byte	$4F
	.byte	$00
	.byte	$06
	.byte	$10
	.byte	$3F
	.byte	$80
	.byte	$80
_topleft:
	.byte	$00
	.byte	$00
	.byte	$50
	.byte	$00
	.byte	$80
_bottomleft:
	.byte	$00
	.byte	$00
	.byte	$51
	.byte	$00
	.byte	$80
.segment	"BANK1"
.segment	"BANK2"
_stage1_level0_0:
	.byte	$3C
	.byte	$1E
	.byte	$1F
	.byte	$50
	.byte	$8B
	.byte	$86
	.byte	$2D
	.byte	$87
	.byte	$7B
	.byte	$86
	.byte	$2D
	.byte	$2D
	.byte	$92
	.byte	$94
	.byte	$89
	.byte	$94
	.byte	$00
	.byte	$01
	.byte	$1E
	.byte	$1F
	.byte	$86
	.byte	$93
	.byte	$2D
	.byte	$2D
	.byte	$87
	.byte	$93
	.byte	$2E
	.byte	$93
	.byte	$2D
	.byte	$2D
	.byte	$89
	.byte	$91
	.byte	$02
	.byte	$03
	.byte	$00
	.byte	$1E
	.byte	$93
	.byte	$92
	.byte	$2E
	.byte	$2D
	.byte	$92
	.byte	$91
	.byte	$2E
	.byte	$2E
	.byte	$93
	.byte	$2D
	.byte	$94
	.byte	$2D
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$91
	.byte	$93
	.byte	$2D
	.byte	$2D
	.byte	$2D
	.byte	$91
	.byte	$89
	.byte	$2D
	.byte	$2D
	.byte	$92
	.byte	$94
	.byte	$91
	.byte	$02
	.byte	$03
	.byte	$15
	.byte	$1B
	.byte	$91
	.byte	$2D
	.byte	$2D
	.byte	$2D
	.byte	$89
	.byte	$90
	.byte	$88
	.byte	$2E
	.byte	$2D
	.byte	$2E
	.byte	$88
	.byte	$91
	.byte	$00
	.byte	$15
	.byte	$CC
	.byte	$CD
	.byte	$29
	.byte	$89
	.byte	$2D
	.byte	$88
	.byte	$2A
	.byte	$46
	.byte	$90
	.byte	$2A
	.byte	$2B
	.byte	$2F
	.byte	$90
	.byte	$88
	.byte	$14
	.byte	$CE
	.byte	$BF
	.byte	$9A
	.byte	$49
	.byte	$90
	.byte	$2C
	.byte	$2A
	.byte	$47
	.byte	$73
	.byte	$48
	.byte	$49
	.byte	$6A
	.byte	$9F
	.byte	$49
	.byte	$2B
	.byte	$CA
	.byte	$C9
	.byte	$CD
	.byte	$50
	.byte	$50
	.byte	$49
	.byte	$62
	.byte	$48
	.byte	$50
	.byte	$71
	.byte	$77
	.byte	$50
	.byte	$69
	.byte	$50
	.byte	$50
	.byte	$9F
	.byte	$C9
	.byte	$CB
	.byte	$51
	.byte	$50
	.byte	$50
	.byte	$66
	.byte	$60
	.byte	$67
	.byte	$50
	.byte	$71
	.byte	$50
	.byte	$6E
	.byte	$69
	.byte	$50
	.byte	$50
	.byte	$76
	.byte	$C9
	.byte	$CB
	.byte	$CD
	.byte	$E2
	.byte	$59
	.byte	$59
	.byte	$61
	.byte	$58
	.byte	$59
	.byte	$72
	.byte	$58
	.byte	$59
	.byte	$68
	.byte	$58
	.byte	$59
	.byte	$58
	.byte	$C9
	.byte	$C9
	.byte	$CB
	.byte	$51
	.byte	$54
	.byte	$63
	.byte	$64
	.byte	$65
	.byte	$74
	.byte	$55
	.byte	$75
	.byte	$52
	.byte	$69
	.byte	$54
	.byte	$51
	.byte	$74
	.byte	$0F
	.byte	$04
	.byte	$04
	.byte	$0C
	.byte	$42
	.byte	$51
	.byte	$55
	.byte	$42
	.byte	$54
	.byte	$55
	.byte	$53
	.byte	$6B
	.byte	$6C
	.byte	$6D
	.byte	$53
	.byte	$51
	.byte	$02
	.byte	$3A
	.byte	$3B
	.byte	$00
	.byte	$0F
	.byte	$06
	.byte	$08
	.byte	$0C
	.byte	$51
	.byte	$40
	.byte	$41
	.byte	$56
	.byte	$55
	.byte	$57
	.byte	$56
	.byte	$56
	.byte	$00
	.byte	$3C
	.byte	$10
	.byte	$02
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$01
	.byte	$0E
	.byte	$07
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$08
	.byte	$09
	.byte	$0A
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$38
	.byte	$38
	.byte	$37
	.byte	$37
	.byte	$38
	.byte	$38
	.byte	$37
	.byte	$38
	.byte	$38
	.byte	$37
	.byte	$37
	.byte	$38
	.byte	$37
_stage1_level0_1:
	.byte	$2D
	.byte	$2E
	.byte	$89
	.byte	$88
	.byte	$89
	.byte	$2E
	.byte	$2E
	.byte	$89
	.byte	$88
	.byte	$89
	.byte	$2E
	.byte	$2E
	.byte	$89
	.byte	$87
	.byte	$50
	.byte	$50
	.byte	$2D
	.byte	$2E
	.byte	$94
	.byte	$93
	.byte	$93
	.byte	$2D
	.byte	$92
	.byte	$2E
	.byte	$94
	.byte	$2E
	.byte	$2E
	.byte	$2E
	.byte	$2E
	.byte	$2E
	.byte	$50
	.byte	$50
	.byte	$2E
	.byte	$2E
	.byte	$2E
	.byte	$91
	.byte	$2D
	.byte	$2E
	.byte	$2D
	.byte	$2E
	.byte	$92
	.byte	$2D
	.byte	$2E
	.byte	$2E
	.byte	$92
	.byte	$2A
	.byte	$50
	.byte	$50
	.byte	$2D
	.byte	$2E
	.byte	$92
	.byte	$88
	.byte	$94
	.byte	$2D
	.byte	$2E
	.byte	$2E
	.byte	$92
	.byte	$93
	.byte	$2E
	.byte	$2E
	.byte	$94
	.byte	$48
	.byte	$50
	.byte	$50
	.byte	$2D
	.byte	$2D
	.byte	$94
	.byte	$89
	.byte	$88
	.byte	$2D
	.byte	$2D
	.byte	$89
	.byte	$2A
	.byte	$2B
	.byte	$2C
	.byte	$2E
	.byte	$2A
	.byte	$DC
	.byte	$DE
	.byte	$50
	.byte	$90
	.byte	$2B
	.byte	$2C
	.byte	$2A
	.byte	$90
	.byte	$2D
	.byte	$2C
	.byte	$2A
	.byte	$46
	.byte	$62
	.byte	$47
	.byte	$2B
	.byte	$48
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$46
	.byte	$62
	.byte	$48
	.byte	$49
	.byte	$46
	.byte	$2F
	.byte	$46
	.byte	$46
	.byte	$48
	.byte	$61
	.byte	$67
	.byte	$9F
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$73
	.byte	$61
	.byte	$DC
	.byte	$DE
	.byte	$9F
	.byte	$6A
	.byte	$73
	.byte	$9E
	.byte	$50
	.byte	$61
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$71
	.byte	$60
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$69
	.byte	$71
	.byte	$77
	.byte	$50
	.byte	$61
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$72
	.byte	$60
	.byte	$58
	.byte	$58
	.byte	$59
	.byte	$68
	.byte	$72
	.byte	$58
	.byte	$59
	.byte	$61
	.byte	$58
	.byte	$59
	.byte	$58
	.byte	$58
	.byte	$58
	.byte	$58
	.byte	$63
	.byte	$64
	.byte	$65
	.byte	$54
	.byte	$52
	.byte	$69
	.byte	$72
	.byte	$52
	.byte	$63
	.byte	$64
	.byte	$65
	.byte	$54
	.byte	$55
	.byte	$54
	.byte	$51
	.byte	$53
	.byte	$55
	.byte	$55
	.byte	$52
	.byte	$42
	.byte	$6B
	.byte	$6C
	.byte	$6D
	.byte	$75
	.byte	$56
	.byte	$55
	.byte	$57
	.byte	$52
	.byte	$51
	.byte	$56
	.byte	$51
	.byte	$52
	.byte	$51
	.byte	$54
	.byte	$55
	.byte	$57
	.byte	$56
	.byte	$41
	.byte	$57
	.byte	$51
	.byte	$51
	.byte	$53
	.byte	$41
	.byte	$40
	.byte	$42
	.byte	$0F
	.byte	$04
	.byte	$0C
	.byte	$0B
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$04
	.byte	$08
	.byte	$06
	.byte	$07
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$0D
	.byte	$00
	.byte	$10
	.byte	$11
	.byte	$37
	.byte	$38
	.byte	$38
	.byte	$37
	.byte	$38
	.byte	$37
	.byte	$37
	.byte	$38
	.byte	$37
	.byte	$38
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$38
_stage1_level0_2:
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$DD
	.byte	$DC
	.byte	$DC
	.byte	$DC
	.byte	$DD
	.byte	$DC
	.byte	$DC
	.byte	$DE
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$DD
	.byte	$DC
	.byte	$DE
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$AC
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$AC
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$AD
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$35
	.byte	$34
	.byte	$A4
	.byte	$A1
	.byte	$BB
	.byte	$BD
	.byte	$B6
	.byte	$BD
	.byte	$BA
	.byte	$B0
	.byte	$BC
	.byte	$B0
	.byte	$BD
	.byte	$BC
	.byte	$35
	.byte	$36
	.byte	$25
	.byte	$21
	.byte	$51
	.byte	$A0
	.byte	$B8
	.byte	$B0
	.byte	$BC
	.byte	$B0
	.byte	$B8
	.byte	$B0
	.byte	$B7
	.byte	$B9
	.byte	$B0
	.byte	$B8
	.byte	$25
	.byte	$21
	.byte	$20
	.byte	$20
	.byte	$A3
	.byte	$A2
	.byte	$AA
	.byte	$A9
	.byte	$B0
	.byte	$A8
	.byte	$AB
	.byte	$B0
	.byte	$A8
	.byte	$A9
	.byte	$35
	.byte	$36
	.byte	$23
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$A5
	.byte	$A6
	.byte	$A6
	.byte	$35
	.byte	$34
	.byte	$34
	.byte	$34
	.byte	$33
	.byte	$34
	.byte	$36
	.byte	$25
	.byte	$21
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$51
	.byte	$51
	.byte	$51
	.byte	$38
	.byte	$37
	.byte	$38
	.byte	$37
	.byte	$37
	.byte	$38
	.byte	$38
	.byte	$23
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
_stage1_level0_3:
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$8B
	.byte	$86
	.byte	$89
	.byte	$2D
	.byte	$89
	.byte	$87
	.byte	$7B
	.byte	$50
	.byte	$DE
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$86
	.byte	$89
	.byte	$2E
	.byte	$88
	.byte	$88
	.byte	$89
	.byte	$87
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$DD
	.byte	$DC
	.byte	$89
	.byte	$93
	.byte	$88
	.byte	$2D
	.byte	$91
	.byte	$2E
	.byte	$94
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$91
	.byte	$89
	.byte	$2E
	.byte	$2D
	.byte	$92
	.byte	$2E
	.byte	$89
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$2C
	.byte	$88
	.byte	$91
	.byte	$2E
	.byte	$88
	.byte	$89
	.byte	$2A
	.byte	$50
	.byte	$50
	.byte	$DD
	.byte	$DC
	.byte	$DC
	.byte	$DE
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$49
	.byte	$2C
	.byte	$90
	.byte	$2B
	.byte	$90
	.byte	$2A
	.byte	$48
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$9F
	.byte	$49
	.byte	$6A
	.byte	$47
	.byte	$48
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$6E
	.byte	$69
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$AD
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$68
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$33
	.byte	$36
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$AC
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$69
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$21
	.byte	$26
	.byte	$35
	.byte	$36
	.byte	$BC
	.byte	$B0
	.byte	$BD
	.byte	$BC
	.byte	$B0
	.byte	$4D
	.byte	$6B
	.byte	$6C
	.byte	$6D
	.byte	$53
	.byte	$4F
	.byte	$BE
	.byte	$20
	.byte	$20
	.byte	$21
	.byte	$26
	.byte	$BD
	.byte	$B8
	.byte	$B0
	.byte	$B7
	.byte	$B6
	.byte	$4A
	.byte	$4B
	.byte	$5A
	.byte	$4B
	.byte	$5B
	.byte	$4C
	.byte	$B6
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$24
	.byte	$35
	.byte	$34
	.byte	$36
	.byte	$B0
	.byte	$A8
	.byte	$B0
	.byte	$B0
	.byte	$B9
	.byte	$B0
	.byte	$A8
	.byte	$AB
	.byte	$A8
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$21
	.byte	$21
	.byte	$26
	.byte	$35
	.byte	$33
	.byte	$34
	.byte	$33
	.byte	$34
	.byte	$33
	.byte	$33
	.byte	$33
	.byte	$36
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$24
	.byte	$38
	.byte	$37
	.byte	$38
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$38
_stage1_level0_4:
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$DD
	.byte	$DC
	.byte	$DC
	.byte	$DE
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$DD
	.byte	$DC
	.byte	$DC
	.byte	$DE
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$DD
	.byte	$DC
	.byte	$DE
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$D1
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$D1
	.byte	$D2
	.byte	$D6
	.byte	$50
	.byte	$50
	.byte	$AC
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$AD
	.byte	$50
	.byte	$D0
	.byte	$D5
	.byte	$D4
	.byte	$D4
	.byte	$B0
	.byte	$B6
	.byte	$B0
	.byte	$BA
	.byte	$B0
	.byte	$BB
	.byte	$7E
	.byte	$78
	.byte	$5F
	.byte	$BA
	.byte	$B0
	.byte	$BA
	.byte	$BD
	.byte	$BE
	.byte	$BA
	.byte	$B0
	.byte	$B8
	.byte	$B0
	.byte	$B9
	.byte	$B0
	.byte	$B7
	.byte	$BC
	.byte	$5C
	.byte	$5D
	.byte	$5E
	.byte	$B6
	.byte	$B7
	.byte	$A9
	.byte	$AB
	.byte	$B7
	.byte	$0E
	.byte	$0D
	.byte	$B0
	.byte	$B9
	.byte	$B0
	.byte	$AA
	.byte	$B0
	.byte	$B7
	.byte	$B0
	.byte	$A8
	.byte	$B7
	.byte	$B0
	.byte	$A9
	.byte	$B0
	.byte	$0E
	.byte	$0D
	.byte	$00
	.byte	$3C
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$0E
	.byte	$07
	.byte	$08
	.byte	$09
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$0C
	.byte	$3A
	.byte	$3B
	.byte	$02
	.byte	$01
	.byte	$51
	.byte	$51
	.byte	$51
	.byte	$38
	.byte	$37
	.byte	$37
	.byte	$38
	.byte	$38
	.byte	$38
	.byte	$38
	.byte	$37
	.byte	$38
	.byte	$38
	.byte	$37
	.byte	$37
	.byte	$38
_stage1_level0_5:
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$DD
	.byte	$DC
	.byte	$DC
	.byte	$DC
	.byte	$DE
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$DD
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$DD
	.byte	$DC
	.byte	$DE
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$D1
	.byte	$D3
	.byte	$50
	.byte	$50
	.byte	$C5
	.byte	$D1
	.byte	$D3
	.byte	$E0
	.byte	$E1
	.byte	$E2
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$D1
	.byte	$D2
	.byte	$D5
	.byte	$0E
	.byte	$50
	.byte	$D0
	.byte	$D4
	.byte	$D6
	.byte	$D7
	.byte	$EC
	.byte	$EB
	.byte	$EA
	.byte	$E3
	.byte	$50
	.byte	$50
	.byte	$D0
	.byte	$D5
	.byte	$D4
	.byte	$D4
	.byte	$00
	.byte	$D2
	.byte	$D4
	.byte	$D4
	.byte	$D4
	.byte	$D9
	.byte	$DA
	.byte	$EE
	.byte	$E9
	.byte	$E9
	.byte	$E4
	.byte	$E5
	.byte	$E6
	.byte	$D4
	.byte	$0F
	.byte	$0C
	.byte	$02
	.byte	$D6
	.byte	$D4
	.byte	$D6
	.byte	$D6
	.byte	$D4
	.byte	$D8
	.byte	$DA
	.byte	$EF
	.byte	$E9
	.byte	$E9
	.byte	$EB
	.byte	$EA
	.byte	$E7
	.byte	$3C
	.byte	$12
	.byte	$3A
	.byte	$0E
	.byte	$07
	.byte	$04
	.byte	$06
	.byte	$04
	.byte	$0C
	.byte	$D8
	.byte	$DB
	.byte	$EE
	.byte	$0E
	.byte	$0C
	.byte	$E9
	.byte	$EB
	.byte	$12
	.byte	$01
	.byte	$12
	.byte	$00
	.byte	$3C
	.byte	$12
	.byte	$02
	.byte	$10
	.byte	$01
	.byte	$BC
	.byte	$B0
	.byte	$BD
	.byte	$00
	.byte	$01
	.byte	$BB
	.byte	$BD
	.byte	$10
	.byte	$03
	.byte	$3C
	.byte	$02
	.byte	$3A
	.byte	$3B
	.byte	$10
	.byte	$12
	.byte	$11
	.byte	$B9
	.byte	$B0
	.byte	$B9
	.byte	$02
	.byte	$03
	.byte	$B8
	.byte	$BC
	.byte	$3A
	.byte	$3B
	.byte	$3C
	.byte	$00
	.byte	$01
	.byte	$3C
	.byte	$3A
	.byte	$3B
	.byte	$01
	.byte	$A9
	.byte	$B6
	.byte	$A9
	.byte	$00
	.byte	$01
	.byte	$B0
	.byte	$A7
	.byte	$00
	.byte	$3C
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$10
	.byte	$3C
	.byte	$10
	.byte	$03
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$02
	.byte	$03
	.byte	$A6
	.byte	$A6
	.byte	$02
	.byte	$01
	.byte	$02
	.byte	$38
	.byte	$37
	.byte	$37
	.byte	$38
	.byte	$37
	.byte	$38
	.byte	$51
	.byte	$51
	.byte	$51
	.byte	$38
	.byte	$38
	.byte	$51
	.byte	$51
	.byte	$38
	.byte	$38
	.byte	$37
_stage1_level0_6:
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$DD
	.byte	$DC
	.byte	$DC
	.byte	$DC
	.byte	$DE
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$DC
	.byte	$DC
	.byte	$DC
	.byte	$DE
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$DD
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$E3
	.byte	$AC
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$DD
	.byte	$DC
	.byte	$DC
	.byte	$DE
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$0A
	.byte	$06
	.byte	$0C
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$D1
	.byte	$D3
	.byte	$E0
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$E4
	.byte	$E2
	.byte	$50
	.byte	$AC
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$C5
	.byte	$D0
	.byte	$D4
	.byte	$D9
	.byte	$EC
	.byte	$02
	.byte	$00
	.byte	$01
	.byte	$0E
	.byte	$08
	.byte	$06
	.byte	$0D
	.byte	$50
	.byte	$50
	.byte	$D1
	.byte	$D2
	.byte	$D4
	.byte	$D6
	.byte	$D4
	.byte	$D5
	.byte	$DB
	.byte	$3B
	.byte	$02
	.byte	$03
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$11
	.byte	$E4
	.byte	$E5
	.byte	$E8
	.byte	$D6
	.byte	$D6
	.byte	$D4
	.byte	$D6
	.byte	$D4
	.byte	$D8
	.byte	$12
	.byte	$3C
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$00
	.byte	$3C
	.byte	$E9
	.byte	$EB
	.byte	$EB
	.byte	$E7
	.byte	$DF
	.byte	$D6
	.byte	$D4
	.byte	$D6
	.byte	$D9
	.byte	$01
	.byte	$3A
	.byte	$3B
	.byte	$00
	.byte	$3C
	.byte	$02
	.byte	$01
	.byte	$0E
	.byte	$0A
	.byte	$0C
	.byte	$B9
	.byte	$BA
	.byte	$BA
	.byte	$B0
	.byte	$BC
	.byte	$B0
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$10
	.byte	$01
	.byte	$02
	.byte	$3A
	.byte	$3B
	.byte	$3C
	.byte	$B8
	.byte	$B0
	.byte	$B8
	.byte	$AB
	.byte	$B9
	.byte	$BA
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$3C
	.byte	$3C
	.byte	$03
	.byte	$00
	.byte	$3C
	.byte	$10
	.byte	$10
	.byte	$A9
	.byte	$AB
	.byte	$A7
	.byte	$B8
	.byte	$B0
	.byte	$AA
	.byte	$03
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$3A
	.byte	$3B
	.byte	$02
	.byte	$10
	.byte	$3C
	.byte	$12
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$A6
	.byte	$0E
	.byte	$09
	.byte	$37
	.byte	$38
	.byte	$38
	.byte	$37
	.byte	$38
	.byte	$38
	.byte	$37
	.byte	$37
	.byte	$38
	.byte	$37
	.byte	$51
	.byte	$51
	.byte	$51
	.byte	$51
	.byte	$10
	.byte	$00
_stage1_level0_7:
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$43
	.byte	$44
	.byte	$19
	.byte	$18
	.byte	$10
	.byte	$3D
	.byte	$00
	.byte	$3C
	.byte	$02
	.byte	$03
	.byte	$02
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$9B
	.byte	$44
	.byte	$19
	.byte	$3D
	.byte	$02
	.byte	$10
	.byte	$10
	.byte	$01
	.byte	$00
	.byte	$DC
	.byte	$DC
	.byte	$DE
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$9F
	.byte	$3D
	.byte	$00
	.byte	$3A
	.byte	$3B
	.byte	$03
	.byte	$02
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$3D
	.byte	$02
	.byte	$3C
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$AD
	.byte	$50
	.byte	$50
	.byte	$3D
	.byte	$00
	.byte	$10
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$E1
	.byte	$E2
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$3E
	.byte	$0E
	.byte	$05
	.byte	$0A
	.byte	$0D
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$3A
	.byte	$3B
	.byte	$E9
	.byte	$E9
	.byte	$E3
	.byte	$50
	.byte	$50
	.byte	$50
	.byte	$3D
	.byte	$3C
	.byte	$03
	.byte	$00
	.byte	$01
	.byte	$10
	.byte	$12
	.byte	$02
	.byte	$3C
	.byte	$00
	.byte	$ED
	.byte	$EF
	.byte	$EB
	.byte	$E3
	.byte	$50
	.byte	$50
	.byte	$3D
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$00
	.byte	$01
	.byte	$11
	.byte	$10
	.byte	$02
	.byte	$DB
	.byte	$DB
	.byte	$E9
	.byte	$EB
	.byte	$E3
	.byte	$AC
	.byte	$3D
	.byte	$02
	.byte	$03
	.byte	$3C
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$3A
	.byte	$3B
	.byte	$00
	.byte	$DA
	.byte	$DB
	.byte	$EF
	.byte	$EB
	.byte	$0F
	.byte	$07
	.byte	$0D
	.byte	$00
	.byte	$01
	.byte	$10
	.byte	$02
	.byte	$00
	.byte	$01
	.byte	$3C
	.byte	$01
	.byte	$02
	.byte	$BC
	.byte	$B0
	.byte	$BD
	.byte	$BC
	.byte	$3C
	.byte	$10
	.byte	$10
	.byte	$02
	.byte	$03
	.byte	$3C
	.byte	$10
	.byte	$02
	.byte	$03
	.byte	$00
	.byte	$02
	.byte	$25
	.byte	$B9
	.byte	$0F
	.byte	$08
	.byte	$0C
	.byte	$00
	.byte	$12
	.byte	$3C
	.byte	$00
	.byte	$01
	.byte	$10
	.byte	$00
	.byte	$3C
	.byte	$01
	.byte	$02
	.byte	$25
	.byte	$20
	.byte	$A9
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$02
	.byte	$10
	.byte	$3C
	.byte	$02
	.byte	$03
	.byte	$00
	.byte	$02
	.byte	$10
	.byte	$02
	.byte	$25
	.byte	$20
	.byte	$20
	.byte	$0D
	.byte	$02
	.byte	$01
	.byte	$02
	.byte	$11
	.byte	$3C
	.byte	$10
	.byte	$00
	.byte	$10
	.byte	$02
	.byte	$25
	.byte	$21
	.byte	$21
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$01
	.byte	$10
	.byte	$01
	.byte	$3A
	.byte	$3B
	.byte	$10
	.byte	$01
	.byte	$02
	.byte	$25
	.byte	$21
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
_stage2_level0_0:
	.byte	$00
	.byte	$04
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$00
	.byte	$04
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$00
	.byte	$04
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$70
	.byte	$71
	.byte	$71
	.byte	$71
	.byte	$72
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$00
	.byte	$04
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$00
	.byte	$04
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$70
	.byte	$71
	.byte	$00
	.byte	$04
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$00
	.byte	$04
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$00
	.byte	$04
	.byte	$71
	.byte	$72
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$3D
	.byte	$00
	.byte	$04
	.byte	$40
	.byte	$3D
	.byte	$40
	.byte	$40
	.byte	$3C
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$3C
	.byte	$40
	.byte	$40
	.byte	$07
	.byte	$09
	.byte	$09
	.byte	$00
	.byte	$04
	.byte	$3B
	.byte	$38
	.byte	$39
	.byte	$38
	.byte	$3B
	.byte	$39
	.byte	$38
	.byte	$3A
	.byte	$38
	.byte	$3A
	.byte	$3B
	.byte	$05
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$04
	.byte	$07
	.byte	$08
	.byte	$0A
	.byte	$38
	.byte	$3A
	.byte	$38
	.byte	$38
	.byte	$38
	.byte	$07
	.byte	$08
	.byte	$0A
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$06
	.byte	$39
	.byte	$38
	.byte	$3A
	.byte	$38
	.byte	$39
	.byte	$05
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$07
	.byte	$08
	.byte	$08
	.byte	$08
	.byte	$0A
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_stage2_level0_1:
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$34
	.byte	$40
	.byte	$0B
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$03
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$34
	.byte	$40
	.byte	$0C
	.byte	$40
	.byte	$40
	.byte	$70
	.byte	$03
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$34
	.byte	$40
	.byte	$0D
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$03
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$34
	.byte	$20
	.byte	$21
	.byte	$22
	.byte	$23
	.byte	$40
	.byte	$03
	.byte	$71
	.byte	$72
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$34
	.byte	$24
	.byte	$25
	.byte	$26
	.byte	$27
	.byte	$40
	.byte	$03
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$34
	.byte	$28
	.byte	$29
	.byte	$CA
	.byte	$2A
	.byte	$C9
	.byte	$03
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$3C
	.byte	$40
	.byte	$3D
	.byte	$40
	.byte	$40
	.byte	$34
	.byte	$2C
	.byte	$2D
	.byte	$C7
	.byte	$2B
	.byte	$3D
	.byte	$03
	.byte	$3C
	.byte	$40
	.byte	$40
	.byte	$07
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$0A
	.byte	$03
	.byte	$08
	.byte	$09
	.byte	$0A
	.byte	$05
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_levels_per_stage:
	.byte	$08
	.byte	$02
_metatile:
	.byte	$7B
	.byte	$7C
	.byte	$8B
	.byte	$8C
	.byte	$00
	.byte	$7D
	.byte	$7E
	.byte	$8D
	.byte	$8E
	.byte	$00
	.byte	$9B
	.byte	$9C
	.byte	$AB
	.byte	$AC
	.byte	$00
	.byte	$9D
	.byte	$9E
	.byte	$AD
	.byte	$AE
	.byte	$00
	.byte	$BE
	.byte	$AF
	.byte	$7B
	.byte	$7C
	.byte	$00
	.byte	$BE
	.byte	$BE
	.byte	$8B
	.byte	$8C
	.byte	$00
	.byte	$BE
	.byte	$BF
	.byte	$8D
	.byte	$8E
	.byte	$00
	.byte	$BE
	.byte	$BE
	.byte	$AD
	.byte	$AE
	.byte	$00
	.byte	$BE
	.byte	$B9
	.byte	$9B
	.byte	$9C
	.byte	$00
	.byte	$BE
	.byte	$BE
	.byte	$9D
	.byte	$9E
	.byte	$00
	.byte	$BE
	.byte	$BB
	.byte	$AB
	.byte	$AC
	.byte	$00
	.byte	$BE
	.byte	$AF
	.byte	$AD
	.byte	$AE
	.byte	$00
	.byte	$BE
	.byte	$BD
	.byte	$7B
	.byte	$7C
	.byte	$00
	.byte	$BE
	.byte	$BD
	.byte	$7D
	.byte	$7E
	.byte	$00
	.byte	$BA
	.byte	$BF
	.byte	$9B
	.byte	$9C
	.byte	$00
	.byte	$BA
	.byte	$B8
	.byte	$9D
	.byte	$9E
	.byte	$00
	.byte	$7B
	.byte	$AE
	.byte	$7C
	.byte	$7B
	.byte	$00
	.byte	$8B
	.byte	$8C
	.byte	$9B
	.byte	$9C
	.byte	$00
	.byte	$8D
	.byte	$8E
	.byte	$9D
	.byte	$9E
	.byte	$00
	.byte	$7B
	.byte	$7C
	.byte	$8B
	.byte	$01
	.byte	$00
	.byte	$AD
	.byte	$8E
	.byte	$AE
	.byte	$01
	.byte	$00
	.byte	$AD
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$7D
	.byte	$7E
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$9D
	.byte	$9E
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$AB
	.byte	$AC
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$7B
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$7B
	.byte	$AD
	.byte	$01
	.byte	$AE
	.byte	$00
	.byte	$7B
	.byte	$7C
	.byte	$01
	.byte	$7B
	.byte	$00
	.byte	$7A
	.byte	$7C
	.byte	$8B
	.byte	$8C
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$7A
	.byte	$00
	.byte	$7B
	.byte	$6A
	.byte	$7C
	.byte	$7B
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$6A
	.byte	$00
	.byte	$00
	.byte	$75
	.byte	$76
	.byte	$85
	.byte	$86
	.byte	$02
	.byte	$65
	.byte	$66
	.byte	$85
	.byte	$86
	.byte	$02
	.byte	$75
	.byte	$76
	.byte	$95
	.byte	$96
	.byte	$02
	.byte	$74
	.byte	$76
	.byte	$84
	.byte	$86
	.byte	$02
	.byte	$75
	.byte	$77
	.byte	$85
	.byte	$87
	.byte	$02
	.byte	$64
	.byte	$66
	.byte	$84
	.byte	$86
	.byte	$02
	.byte	$65
	.byte	$67
	.byte	$85
	.byte	$87
	.byte	$02
	.byte	$74
	.byte	$76
	.byte	$94
	.byte	$96
	.byte	$02
	.byte	$75
	.byte	$77
	.byte	$95
	.byte	$97
	.byte	$02
	.byte	$DF
	.byte	$DF
	.byte	$DC
	.byte	$CD
	.byte	$03
	.byte	$DF
	.byte	$CE
	.byte	$CE
	.byte	$DB
	.byte	$03
	.byte	$CD
	.byte	$CE
	.byte	$EE
	.byte	$EE
	.byte	$03
	.byte	$DF
	.byte	$CF
	.byte	$DC
	.byte	$CC
	.byte	$03
	.byte	$34
	.byte	$CF
	.byte	$DF
	.byte	$33
	.byte	$03
	.byte	$DF
	.byte	$CF
	.byte	$33
	.byte	$CF
	.byte	$03
	.byte	$CB
	.byte	$CE
	.byte	$EF
	.byte	$EE
	.byte	$03
	.byte	$65
	.byte	$66
	.byte	$95
	.byte	$96
	.byte	$02
	.byte	$64
	.byte	$66
	.byte	$94
	.byte	$96
	.byte	$02
	.byte	$65
	.byte	$67
	.byte	$95
	.byte	$97
	.byte	$02
	.byte	$EB
	.byte	$EB
	.byte	$FB
	.byte	$FC
	.byte	$03
	.byte	$EB
	.byte	$EA
	.byte	$FC
	.byte	$FB
	.byte	$03
	.byte	$FA
	.byte	$EB
	.byte	$FC
	.byte	$FC
	.byte	$03
	.byte	$EB
	.byte	$EC
	.byte	$FB
	.byte	$FC
	.byte	$03
	.byte	$98
	.byte	$99
	.byte	$A8
	.byte	$A9
	.byte	$03
	.byte	$9A
	.byte	$98
	.byte	$AA
	.byte	$A8
	.byte	$03
	.byte	$01
	.byte	$01
	.byte	$9A
	.byte	$98
	.byte	$03
	.byte	$7B
	.byte	$8B
	.byte	$AD
	.byte	$9B
	.byte	$00
	.byte	$8E
	.byte	$7B
	.byte	$9C
	.byte	$AE
	.byte	$00
	.byte	$8B
	.byte	$7C
	.byte	$9B
	.byte	$AD
	.byte	$00
	.byte	$0A
	.byte	$0B
	.byte	$0A
	.byte	$0B
	.byte	$02
	.byte	$0A
	.byte	$0B
	.byte	$0A
	.byte	$0B
	.byte	$02
	.byte	$CA
	.byte	$CA
	.byte	$DA
	.byte	$DA
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$63
	.byte	$73
	.byte	$03
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$63
	.byte	$03
	.byte	$01
	.byte	$01
	.byte	$73
	.byte	$01
	.byte	$03
	.byte	$12
	.byte	$13
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$12
	.byte	$13
	.byte	$00
	.byte	$EF
	.byte	$9F
	.byte	$01
	.byte	$01
	.byte	$03
	.byte	$EF
	.byte	$EF
	.byte	$EE
	.byte	$EF
	.byte	$03
	.byte	$ED
	.byte	$ED
	.byte	$36
	.byte	$37
	.byte	$03
	.byte	$ED
	.byte	$38
	.byte	$37
	.byte	$00
	.byte	$03
	.byte	$39
	.byte	$ED
	.byte	$00
	.byte	$39
	.byte	$03
	.byte	$02
	.byte	$0D
	.byte	$0E
	.byte	$02
	.byte	$03
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$1F
	.byte	$02
	.byte	$02
	.byte	$2F
	.byte	$03
	.byte	$1B
	.byte	$0C
	.byte	$02
	.byte	$01
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0F
	.byte	$3F
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$2A
	.byte	$01
	.byte	$03
	.byte	$1A
	.byte	$01
	.byte	$01
	.byte	$2A
	.byte	$03
	.byte	$1A
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$03
	.byte	$F2
	.byte	$F2
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$F3
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$D4
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$80
	.byte	$81
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$82
	.byte	$82
	.byte	$03
	.byte	$01
	.byte	$2A
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$1A
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$AA
	.byte	$03
	.byte	$E8
	.byte	$03
	.byte	$A8
	.byte	$A9
	.byte	$68
	.byte	$FC
	.byte	$03
	.byte	$8A
	.byte	$03
	.byte	$F8
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$E9
	.byte	$03
	.byte	$03
	.byte	$08
	.byte	$19
	.byte	$09
	.byte	$18
	.byte	$02
	.byte	$08
	.byte	$19
	.byte	$08
	.byte	$18
	.byte	$02
	.byte	$B1
	.byte	$B2
	.byte	$08
	.byte	$18
	.byte	$02
	.byte	$D4
	.byte	$B0
	.byte	$F3
	.byte	$C0
	.byte	$02
	.byte	$08
	.byte	$19
	.byte	$C1
	.byte	$C2
	.byte	$02
	.byte	$B3
	.byte	$F3
	.byte	$C3
	.byte	$D4
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$F0
	.byte	$02
	.byte	$F1
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$14
	.byte	$04
	.byte	$15
	.byte	$04
	.byte	$02
	.byte	$15
	.byte	$04
	.byte	$15
	.byte	$05
	.byte	$02
	.byte	$E5
	.byte	$E6
	.byte	$14
	.byte	$04
	.byte	$02
	.byte	$D4
	.byte	$E4
	.byte	$F3
	.byte	$F4
	.byte	$02
	.byte	$14
	.byte	$04
	.byte	$F5
	.byte	$F6
	.byte	$02
	.byte	$E7
	.byte	$F3
	.byte	$F7
	.byte	$D4
	.byte	$02
	.byte	$00
	.byte	$E2
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$E3
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$17
	.byte	$06
	.byte	$17
	.byte	$02
	.byte	$07
	.byte	$16
	.byte	$07
	.byte	$17
	.byte	$02
	.byte	$06
	.byte	$17
	.byte	$07
	.byte	$17
	.byte	$02
	.byte	$E0
	.byte	$E1
	.byte	$06
	.byte	$16
	.byte	$02
	.byte	$D4
	.byte	$D0
	.byte	$F2
	.byte	$F2
	.byte	$02
	.byte	$D1
	.byte	$F3
	.byte	$F2
	.byte	$F2
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$D2
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$D3
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$AA
	.byte	$AA
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$A9
	.byte	$A9
	.byte	$78
	.byte	$69
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$89
	.byte	$00
	.byte	$03
	.byte	$8A
	.byte	$00
	.byte	$8A
	.byte	$00
	.byte	$03
	.byte	$8A
	.byte	$00
	.byte	$79
	.byte	$00
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$F9
	.byte	$03
	.byte	$F9
	.byte	$E9
	.byte	$AA
	.byte	$AA
	.byte	$03
	.byte	$90
	.byte	$90
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$91
	.byte	$92
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$92
	.byte	$92
	.byte	$02
	.byte	$92
	.byte	$90
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$92
	.byte	$90
	.byte	$02
	.byte	$01
	.byte	$92
	.byte	$90
	.byte	$00
	.byte	$02
	.byte	$7A
	.byte	$32
	.byte	$32
	.byte	$DF
	.byte	$03
	.byte	$CF
	.byte	$89
	.byte	$DF
	.byte	$CF
	.byte	$03
	.byte	$DF
	.byte	$33
	.byte	$DE
	.byte	$DF
	.byte	$03
	.byte	$DD
	.byte	$CF
	.byte	$DF
	.byte	$34
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$7A
	.byte	$03
	.byte	$AA
	.byte	$A8
	.byte	$68
	.byte	$69
	.byte	$03
	.byte	$AA
	.byte	$A8
	.byte	$68
	.byte	$68
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$D7
	.byte	$A7
	.byte	$00
	.byte	$D7
	.byte	$A7
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$DF
	.byte	$CF
	.byte	$DC
	.byte	$DB
	.byte	$03
	.byte	$32
	.byte	$33
	.byte	$DE
	.byte	$DF
	.byte	$03
	.byte	$DF
	.byte	$35
	.byte	$CF
	.byte	$DD
	.byte	$03
	.byte	$32
	.byte	$34
	.byte	$32
	.byte	$33
	.byte	$03
	.byte	$33
	.byte	$35
	.byte	$34
	.byte	$35
	.byte	$03
	.byte	$00
	.byte	$7A
	.byte	$88
	.byte	$DF
	.byte	$03
	.byte	$00
	.byte	$88
	.byte	$88
	.byte	$CF
	.byte	$03
	.byte	$6A
	.byte	$00
	.byte	$CF
	.byte	$6A
	.byte	$03
	.byte	$89
	.byte	$00
	.byte	$A8
	.byte	$89
	.byte	$03
	.byte	$A9
	.byte	$6A
	.byte	$A9
	.byte	$AA
	.byte	$03
	.byte	$01
	.byte	$FF
	.byte	$FF
	.byte	$00
	.byte	$03
	.byte	$FF
	.byte	$01
	.byte	$00
	.byte	$FE
	.byte	$03
	.byte	$EF
	.byte	$EF
	.byte	$FE
	.byte	$FD
	.byte	$03
	.byte	$ED
	.byte	$EE
	.byte	$FE
	.byte	$FF
	.byte	$03
	.byte	$FD
	.byte	$FE
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$FF
	.byte	$FD
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$03
	.byte	$03
	.byte	$3F
	.byte	$03
	.byte	$05
	.byte	$03
	.byte	$03
	.byte	$05
	.byte	$03
	.byte	$2F
	.byte	$03
	.byte	$03
	.byte	$01
	.byte	$1F
	.byte	$1F
	.byte	$02
	.byte	$03
	.byte	$0F
	.byte	$02
	.byte	$01
	.byte	$0F
	.byte	$03
	.byte	$02
	.byte	$2F
	.byte	$11
	.byte	$11
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$11
	.byte	$11
	.byte	$03
	.byte	$03
	.byte	$61
	.byte	$60
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$62
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$61
	.byte	$03
	.byte	$03
	.byte	$60
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$72
	.byte	$03
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$71
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$70
	.byte	$03
	.byte	$C8
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$C8
	.byte	$C9
	.byte	$01
	.byte	$D9
	.byte	$01
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$3F
	.byte	$03
	.byte	$02
	.byte	$3F
	.byte	$03
	.byte	$01
	.byte	$01
	.byte	$0D
	.byte	$01
	.byte	$03
	.byte	$03
	.byte	$0E
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$A1
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$A2
	.byte	$03
	.byte	$03
	.byte	$A2
	.byte	$03
	.byte	$03
	.byte	$A1
	.byte	$03
	.byte	$A0
	.byte	$03
	.byte	$03
	.byte	$A1
	.byte	$03
	.byte	$83
	.byte	$03
	.byte	$03
	.byte	$83
	.byte	$03
	.byte	$83
	.byte	$93
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$83
	.byte	$03
	.byte	$03
	.byte	$93
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$83
	.byte	$03
	.byte	$03
	.byte	$83
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$C9
	.byte	$D9
	.byte	$D8
	.byte	$01
	.byte	$01
	.byte	$B5
	.byte	$B6
	.byte	$C5
	.byte	$C6
	.byte	$02
	.byte	$01
	.byte	$B4
	.byte	$01
	.byte	$C4
	.byte	$02
	.byte	$B7
	.byte	$01
	.byte	$C7
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$A5
	.byte	$A6
	.byte	$02
	.byte	$D5
	.byte	$D6
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$6B
	.byte	$6B
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$10
	.byte	$10
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$9F
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$C8
	.byte	$C9
	.byte	$D8
	.byte	$D9
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$D8
	.byte	$D9
	.byte	$01
	.byte	$C8
	.byte	$01
	.byte	$D8
	.byte	$D9
	.byte	$01
	.byte	$01
	.byte	$C9
	.byte	$D8
	.byte	$D9
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$D8
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$D9
	.byte	$01
	.byte	$01
	.byte	$D9
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$5E
	.byte	$6C
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$6B
	.byte	$6C
	.byte	$00
	.byte	$6B
	.byte	$5E
	.byte	$03
	.byte	$6D
	.byte	$00
	.byte	$6B
	.byte	$5E
	.byte	$6D
	.byte	$5D
	.byte	$00
	.byte	$6D
	.byte	$03
	.byte	$03
	.byte	$6D
	.byte	$00
	.byte	$6D
	.byte	$6D
	.byte	$03
	.byte	$03
	.byte	$00
	.byte	$6D
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$00
	.byte	$6D
	.byte	$40
	.byte	$6D
	.byte	$40
	.byte	$00
	.byte	$40
	.byte	$6E
	.byte	$6F
	.byte	$40
	.byte	$00
	.byte	$6D
	.byte	$14
	.byte	$03
	.byte	$6F
	.byte	$00
	.byte	$40
	.byte	$6E
	.byte	$40
	.byte	$40
	.byte	$00
	.byte	$6E
	.byte	$6E
	.byte	$40
	.byte	$6E
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$1E
	.byte	$1E
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$1C
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$1D
	.byte	$00
	.byte	$01
	.byte	$6D
	.byte	$6D
	.byte	$A3
	.byte	$A4
	.byte	$00
	.byte	$5D
	.byte	$5B
	.byte	$40
	.byte	$9F
	.byte	$00
	.byte	$5C
	.byte	$80
	.byte	$9F
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$5B
	.byte	$5C
	.byte	$00
	.byte	$5F
	.byte	$00
	.byte	$9F
	.byte	$5F
	.byte	$00
	.byte	$5B
	.byte	$5C
	.byte	$9F
	.byte	$01
	.byte	$00
	.byte	$6B
	.byte	$6C
	.byte	$01
	.byte	$A3
	.byte	$00
	.byte	$6D
	.byte	$03
	.byte	$A4
	.byte	$03
	.byte	$00
	.byte	$A3
	.byte	$A4
	.byte	$9F
	.byte	$9F
	.byte	$00
	.byte	$03
	.byte	$6D
	.byte	$A4
	.byte	$03
	.byte	$00
	.byte	$9F
	.byte	$9F
	.byte	$9F
	.byte	$9F
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$9F
	.byte	$9F
	.byte	$00
	.byte	$9F
	.byte	$01
	.byte	$9F
	.byte	$9F
	.byte	$00
	.byte	$6E
	.byte	$9F
	.byte	$6E
	.byte	$8F
	.byte	$00
	.byte	$8F
	.byte	$7F
	.byte	$6E
	.byte	$6E
	.byte	$00
	.byte	$9F
	.byte	$9F
	.byte	$8F
	.byte	$7F
	.byte	$00
	.byte	$7F
	.byte	$9F
	.byte	$6E
	.byte	$8F
	.byte	$00
.segment	"BANK3"
.segment	"BANK4"
.segment	"BANK5"
.segment	"BANK6"
.segment	"CODE"
_palette_bg:
	.byte	$21
	.byte	$0F
	.byte	$00
	.byte	$10
	.byte	$21
	.byte	$0F
	.byte	$30
	.byte	$08
	.byte	$21
	.byte	$0F
	.byte	$17
	.byte	$06
	.byte	$21
	.byte	$0F
	.byte	$19
	.byte	$29
_palette_sp:
	.byte	$21
	.byte	$17
	.byte	$24
	.byte	$36
	.byte	$21
	.byte	$05
	.byte	$16
	.byte	$37
	.byte	$21
	.byte	$0F
	.byte	$11
	.byte	$30
	.byte	$21
	.byte	$17
	.byte	$3D
	.byte	$37

.segment	"BSS"

_bankLevel:
	.res	1,$00
_bankBuffer:
	.res	10,$00
.segment	"ZEROPAGE"
_direction:
	.res	1,$00
_direction_y:
	.res	1,$00
_arg1:
	.res	1,$00
_arg2:
	.res	1,$00
_pad1:
	.res	1,$00
_pad1_new:
	.res	1,$00
_char_state:
	.res	1,$00
_song:
	.res	1,$00
_sound:
	.res	1,$00
_temp_x:
	.res	2,$00
_temp_y:
	.res	2,$00
_temp_sprite:
	.res	2,$00
_old_x:
	.res	1,$00
_old_y:
	.res	1,$00
_eject_L:
	.res	1,$00
_eject_R:
	.res	1,$00
_eject_D:
	.res	1,$00
_eject_U:
	.res	1,$00
_collision_L:
	.res	1,$00
_collision_R:
	.res	1,$00
_collision_U:
	.res	1,$00
_collision_D:
	.res	1,$00
_coordinates:
	.res	1,$00
_location_with_scroll:
	.res	2,$00
_collision:
	.res	1,$00
_map_loaded:
	.res	1,$00
_scrolling_direction:
	.res	1,$00
_nametable_to_load:
	.res	1,$00
_offset:
	.res	1,$00
_address:
	.res	2,$00
_x:
	.res	1,$00
_y:
	.res	1,$00
_nt:
	.res	1,$00
_index:
	.res	1,$00
_map:
	.res	1,$00
_scroll_x:
	.res	2,$00
_max_rooms:
	.res	1,$00
_max_scroll:
	.res	2,$00
_temp_room:
	.res	1,$00
_scroll_count:
	.res	1,$00
_pseudo_scroll_x:
	.res	2,$00
.segment	"BSS"
_c_map:
	.res	240,$00
_c_map2:
	.res	240,$00
_temp1:
	.res	2,$00
_temp2:
	.res	2,$00
_temp3:
	.res	2,$00
_l_scroll_frames:
	.res	1,$00
_r_scroll_frames:
	.res	1,$00
_Generic:
	.res	4,$00
_Generic2:
	.res	4,$00
.segment	"XRAM"
_wram_array:
	.res	8192,$00

; ---------------------------------------------------------------
; void __near__ banked_call (unsigned char, __near__ __near__ function returning void *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_banked_call: near

.segment	"CODE"

;
; void banked_call(unsigned char bankId, void (*method)(void)) {
;
	jsr     pushax
;
; bank_push(bankId);
;
	ldy     #$02
	lda     (sp),y
	jsr     _bank_push
;
; (*method)();
;
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     callax
;
; bank_pop();
;
	jsr     _bank_pop
;
; }
;
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ bank_push (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_bank_push: near

.segment	"CODE"

;
; void bank_push(unsigned char bankId) {
;
	jsr     pusha
;
; bankBuffer[bankLevel] = get_prg_bank();
;
	lda     #<(_bankBuffer)
	ldx     #>(_bankBuffer)
	clc
	adc     _bankLevel
	bcc     L000B
	inx
L000B:	jsr     pushax
	jsr     _get_prg_bank
	ldy     #$00
	jsr     staspidx
;
; ++bankLevel;
;
	inc     _bankLevel
;
; set_prg_bank(bankId);
;
	ldy     #$00
	lda     (sp),y
	jsr     _set_prg_bank
;
; }
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ bank_pop (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_bank_pop: near

.segment	"CODE"

;
; if (bankLevel != 0) {
;
	lda     _bankLevel
	beq     L0011
;
; --bankLevel;
;
	dec     _bankLevel
;
; set_prg_bank(bankBuffer[bankLevel]);
;
	ldy     _bankLevel
	lda     _bankBuffer,y
	jmp     _set_prg_bank
;
; }
;
L0011:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_collision_sub (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_collision_sub: near

.segment	"BANK0"

;
; if (temp_y >= 0xf0)
;
	lda     _temp_y
	cmp     #$F0
	lda     _temp_y+1
	sbc     #$00
	bcc     L0139
;
; return 0;
;
	ldx     #$00
	txa
	rts
;
; coordinates = (temp_x >> 4) + (temp_y & 0xf0);
;
L0139:	lda     _temp_x
	ldx     _temp_x+1
	jsr     shrax4
	sta     ptr1
	lda     _temp_y
	and     #$F0
	clc
	adc     ptr1
	sta     _coordinates
;
; map = temp_room & 1; // high byte
;
	lda     _temp_room
	and     #$01
	sta     _map
;
; if (!map)
;
	lda     _map
	bne     L0142
;
; collision = c_map[coordinates];
;
	ldy     _coordinates
	lda     _c_map,y
;
; else
;
	jmp     L12F4
;
; collision = c_map2[coordinates];
;
L0142:	ldy     _coordinates
	lda     _c_map2,y
L12F4:	sta     _collision
;
; return metatile_colision_map[collision];
;
	ldy     _collision
	ldx     #$00
	lda     _metatile_colision_map,y
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ bg_collision_fast (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_collision_fast: near

.segment	"BANK0"

;
; collision_L = 0;
;
	lda     #$00
	sta     _collision_L
;
; collision_R = 0;
;
	sta     _collision_R
;
; collision_D = 0;
;
	sta     _collision_D
;
; if (Generic.y >= 0xf0)
;
	lda     _Generic+1
	cmp     #$F0
;
; return;
;
	bcc     L12F8
;
; }
;
	rts
;
; location_with_scroll = Generic.x + scroll_x;
;
L12F8:	lda     _Generic
	clc
	adc     _scroll_x
	pha
	lda     #$00
	adc     _scroll_x+1
	sta     _location_with_scroll+1
	pla
	sta     _location_with_scroll
;
; temp_x = location_with_scroll & 0xff;  // low byte x
;
	ldx     #$00
	sta     _temp_x
	stx     _temp_x+1
;
; temp_room = location_with_scroll >> 8; // high byte x
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; temp_y = Generic.y + 6; // y middle
;
	lda     _Generic+1
	clc
	adc     #$06
	bcc     L0161
	inx
L0161:	sta     _temp_y
	stx     _temp_y+1
;
; bg_collision_sub();
;
	jsr     _bg_collision_sub
;
; if (bg_collision_sub() & COL_ALL)
;
	jsr     _bg_collision_sub
	and     #$40
	beq     L12F6
;
; ++collision_L;
;
	inc     _collision_L
;
; location_with_scroll += Generic.width;
;
L12F6:	lda     _Generic+2
	clc
	adc     _location_with_scroll
	sta     _location_with_scroll
	lda     #$00
	adc     _location_with_scroll+1
	sta     _location_with_scroll+1
;
; temp_x = location_with_scroll & 0xff;  // low byte x
;
	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_room = location_with_scroll >> 8; // high byte x
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; bg_collision_sub();
;
	jsr     _bg_collision_sub
;
; if (bg_collision_sub() & COL_ALL)
;
	jsr     _bg_collision_sub
	and     #$40
	beq     L12F7
;
; ++collision_R;
;
	inc     _collision_R
;
; location_with_scroll -= (Generic.width >> 1); // middle of character
;
L12F7:	lda     _Generic+2
	lsr     a
	eor     #$FF
	sec
	adc     _location_with_scroll
	sta     _location_with_scroll
	lda     #$FF
	adc     _location_with_scroll+1
	sta     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll;          // low byte
;
	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_y += 6;
;
	lda     #$06
	clc
	adc     _temp_y
	sta     _temp_y
	bcc     L0177
	inc     _temp_y+1
;
; if (bg_collision_sub() & COL_ALL)
;
L0177:	jsr     _bg_collision_sub
	and     #$40
	beq     L0178
;
; ++collision_D;
;
	inc     _collision_D
;
; }
;
L0178:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_coll_L (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_coll_L: near

.segment	"BANK0"

;
; location_with_scroll = Generic.x + scroll_x;
;
	lda     _Generic
	clc
	adc     _scroll_x
	sta     _location_with_scroll
	lda     #$00
	adc     _scroll_x+1
	sta     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll;   // low byte
;
	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_room = location_with_scroll >> 8; // high byte
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; eject_L = temp_x | 0xf0;
;
	lda     _temp_x
	ora     #$F0
	sta     _eject_L
;
; temp_y = Generic.y + 2;
;
	ldx     #$00
	lda     _Generic+1
	clc
	adc     #$02
	bcc     L0186
	inx
L0186:	sta     _temp_y
	stx     _temp_y+1
;
; if (bg_collision_sub() & COL_ALL)
;
	jsr     _bg_collision_sub
	ldx     #$00
	and     #$40
	beq     L12FA
;
; return 1;
;
	lda     #$01
	rts
;
; temp_y = Generic.y + Generic.height;
;
L12FA:	lda     _Generic+1
	clc
	adc     _Generic+3
	bcc     L12F9
	inx
L12F9:	sta     _temp_y
	stx     _temp_y+1
;
; temp_y -= 2;
;
	lda     _temp_y
	sec
	sbc     #$02
	sta     _temp_y
	bcs     L018E
	dec     _temp_y+1
;
; if (bg_collision_sub() & COL_ALL)
;
L018E:	jsr     _bg_collision_sub
	ldx     #$00
	and     #$40
	beq     L12FC
;
; return 1;
;
	lda     #$01
	rts
;
; }
;
L12FC:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_coll_R (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_coll_R: near

.segment	"BANK0"

;
; location_with_scroll = Generic.x + scroll_x + Generic.width;
;
	lda     _Generic
	clc
	adc     _scroll_x
	pha
	lda     #$00
	adc     _scroll_x+1
	tax
	pla
	clc
	adc     _Generic+2
	bcc     L12FD
	inx
L12FD:	sta     _location_with_scroll
	stx     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll;   // low byte
;
	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_room = location_with_scroll >> 8; // high byte
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; eject_R = (temp_x + 1) & 0x0f;
;
	lda     _temp_x
	clc
	adc     #$01
	and     #$0F
	sta     _eject_R
;
; temp_y = Generic.y + 2;
;
	ldx     #$00
	lda     _Generic+1
	clc
	adc     #$02
	bcc     L01A0
	inx
L01A0:	sta     _temp_y
	stx     _temp_y+1
;
; if (bg_collision_sub() & COL_ALL)
;
	jsr     _bg_collision_sub
	ldx     #$00
	and     #$40
	beq     L12FF
;
; return 1;
;
	lda     #$01
	rts
;
; temp_y = Generic.y + Generic.height;
;
L12FF:	lda     _Generic+1
	clc
	adc     _Generic+3
	bcc     L12FE
	inx
L12FE:	sta     _temp_y
	stx     _temp_y+1
;
; temp_y -= 2;
;
	lda     _temp_y
	sec
	sbc     #$02
	sta     _temp_y
	bcs     L01A8
	dec     _temp_y+1
;
; if (bg_collision_sub() & COL_ALL)
;
L01A8:	jsr     _bg_collision_sub
	ldx     #$00
	and     #$40
	beq     L1301
;
; return 1;
;
	lda     #$01
	rts
;
; }
;
L1301:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_coll_ladder (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_coll_ladder: near

.segment	"BANK0"

;
; location_with_scroll = Generic.x + scroll_x + 7;
;
	lda     _Generic
	clc
	adc     _scroll_x
	pha
	lda     #$00
	adc     _scroll_x+1
	tax
	pla
	clc
	adc     #$07
	bcc     L01B0
	inx
L01B0:	sta     _location_with_scroll
	stx     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll; // low byte
;
	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_y = Generic.y + Generic.height;
;
	ldx     #$00
	lda     _Generic+1
	clc
	adc     _Generic+3
	bcc     L1302
	inx
L1302:	sta     _temp_y
	stx     _temp_y+1
;
; temp_y -= 2;
;
	lda     _temp_y
	sec
	sbc     #$02
	sta     _temp_y
	bcs     L01B7
	dec     _temp_y+1
;
; if (bg_collision_sub() & COL_LADDER || bg_collision_sub() & COL_LADDER_TOP)
;
L01B7:	jsr     _bg_collision_sub
	and     #$01
	bne     L1303
	jsr     _bg_collision_sub
	and     #$02
	bne     L1303
	tax
	rts
;
; return location_with_scroll;
;
L1303:	ldx     #$00
	lda     _location_with_scroll
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_coll_ladder_top_at_player (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_coll_ladder_top_at_player: near

.segment	"BANK0"

;
; location_with_scroll = Generic.x + scroll_x + 7;
;
	lda     _Generic
	clc
	adc     _scroll_x
	pha
	lda     #$00
	adc     _scroll_x+1
	tax
	pla
	clc
	adc     #$07
	bcc     L01C0
	inx
L01C0:	sta     _location_with_scroll
	stx     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll; // low byte
;
	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_y = Generic.y + Generic.height;
;
	ldx     #$00
	lda     _Generic+1
	clc
	adc     _Generic+3
	bcc     L1306
	inx
L1306:	sta     _temp_y
	stx     _temp_y+1
;
; temp_y -= 2;
;
	lda     _temp_y
	sec
	sbc     #$02
	sta     _temp_y
	bcs     L01C7
	dec     _temp_y+1
;
; if (bg_collision_sub() & COL_LADDER)
;
L01C7:	jsr     _bg_collision_sub
	ldx     #$00
	and     #$01
	beq     L1308
;
; return 1;
;
	lda     #$01
	rts
;
; }
;
L1308:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_coll_ladder_top_under_player (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_coll_ladder_top_under_player: near

.segment	"BANK0"

;
; location_with_scroll = Generic.x + scroll_x + 7;
;
	lda     _Generic
	clc
	adc     _scroll_x
	pha
	lda     #$00
	adc     _scroll_x+1
	tax
	pla
	clc
	adc     #$07
	bcc     L01CF
	inx
L01CF:	sta     _location_with_scroll
	stx     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll; // low byte
;
	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_y = Generic.y + Generic.height;
;
	ldx     #$00
	lda     _Generic+1
	clc
	adc     _Generic+3
	bcc     L1309
	inx
L1309:	sta     _temp_y
	stx     _temp_y+1
;
; temp_y += 4;
;
	lda     #$04
	clc
	adc     _temp_y
	sta     _temp_y
	bcc     L01D6
	inc     _temp_y+1
;
; if (bg_collision_sub() & COL_LADDER_TOP)
;
L01D6:	jsr     _bg_collision_sub
	ldx     #$00
	and     #$02
	beq     L130B
;
; return 1;
;
	lda     #$01
	rts
;
; }
;
L130B:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_coll_U (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_coll_U: near

.segment	"BANK0"

;
; location_with_scroll = Generic.x + scroll_x;
;
	lda     _Generic
	clc
	adc     _scroll_x
	sta     _location_with_scroll
	lda     #$00
	adc     _scroll_x+1
	sta     _location_with_scroll+1
;
; location_with_scroll += 2;
;
	lda     #$02
	clc
	adc     _location_with_scroll
	sta     _location_with_scroll
	bcc     L01E0
	inc     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll;   // low byte
;
L01E0:	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_room = location_with_scroll >> 8; // high byte
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; temp_y = Generic.y;
;
	lda     #$00
	sta     _temp_y+1
	lda     _Generic+1
	sta     _temp_y
;
; eject_U = temp_y | 0xf0;
;
	ora     #$F0
	sta     _eject_U
;
; if (bg_collision_sub() & COL_ALL)
;
	jsr     _bg_collision_sub
	and     #$40
	beq     L130D
;
; return 1;
;
	ldx     #$00
	lda     #$01
	rts
;
; location_with_scroll = Generic.x + scroll_x + Generic.width;
;
L130D:	lda     _Generic
	clc
	adc     _scroll_x
	pha
	lda     #$00
	adc     _scroll_x+1
	tax
	pla
	clc
	adc     _Generic+2
	bcc     L130C
	inx
L130C:	sta     _location_with_scroll
	stx     _location_with_scroll+1
;
; location_with_scroll -= 2;
;
	lda     _location_with_scroll
	sec
	sbc     #$02
	sta     _location_with_scroll
	bcs     L01F0
	dec     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll;   // low byte
;
L01F0:	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_room = location_with_scroll >> 8; // high byte
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; if (bg_collision_sub() & COL_ALL)
;
	jsr     _bg_collision_sub
	ldx     #$00
	and     #$40
	beq     L130F
;
; return 1;
;
	lda     #$01
	rts
;
; }
;
L130F:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_coll_D (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_coll_D: near

.segment	"BANK0"

;
; location_with_scroll = Generic.x + scroll_x;
;
	lda     _Generic
	clc
	adc     _scroll_x
	sta     _location_with_scroll
	lda     #$00
	adc     _scroll_x+1
	sta     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll;   // low byte
;
	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_room = location_with_scroll >> 8; // high byte
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; temp_y = Generic.y + Generic.height;
;
	ldx     #$00
	lda     _Generic+1
	clc
	adc     _Generic+3
	bcc     L1310
	inx
L1310:	sta     _temp_y
	stx     _temp_y+1
;
; if ((temp_y & 0x0f) > 3)
;
	and     #$0F
	cmp     #$04
	lda     #$00
	bcc     L0202
;
; return 0; // bug fix
;
	tax
	rts
;
; eject_D = (temp_y + 1) & 0x0f;
;
L0202:	lda     _temp_y
	clc
	adc     #$01
	and     #$0F
	sta     _eject_D
;
; if (bg_collision_sub() & COL_ALL || ((bg_collision_sub() & COL_LADDER_TOP)))
;
	jsr     _bg_collision_sub
	and     #$40
	bne     L1313
	jsr     _bg_collision_sub
	and     #$02
	beq     L1314
;
; return 1;
;
L1313:	ldx     #$00
	lda     #$01
	rts
;
; location_with_scroll = Generic.x + scroll_x + Generic.width;
;
L1314:	lda     _Generic
	clc
	adc     _scroll_x
	pha
	lda     #$00
	adc     _scroll_x+1
	tax
	pla
	clc
	adc     _Generic+2
	bcc     L1311
	inx
L1311:	sta     _location_with_scroll
	stx     _location_with_scroll+1
;
; location_with_scroll -= 2;
;
	lda     _location_with_scroll
	sec
	sbc     #$02
	sta     _location_with_scroll
	bcs     L0214
	dec     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll;   // low byte
;
L0214:	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_room = location_with_scroll >> 8; // high byte
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; if (bg_collision_sub() & COL_ALL || ((bg_collision_sub() & COL_LADDER_TOP)))
;
	jsr     _bg_collision_sub
	and     #$40
	bne     L1315
	jsr     _bg_collision_sub
	and     #$02
	bne     L1315
	tax
	rts
;
; return 1;
;
L1315:	ldx     #$00
	lda     #$01
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ move_player (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_move_player: near

.segment	"BANK0"

;
; old_x = Player1.x; 
;
	lda     _Player1
	sta     _old_x
;
; if (pad1 & PAD_LEFT )
;
	lda     _pad1
	and     #$02
	beq     L1318
;
; direction = LEFT;
;
	lda     #$00
	sta     _direction
;
; if (Player1.vel_x >= DECEL)
;
	lda     _Player1+4
	cmp     #$32
	lda     _Player1+4+1
	sbc     #$00
	bvs     L0229
	eor     #$80
L0229:	bpl     L0227
;
; Player1.vel_x -= DECEL;
;
	lda     _Player1+4
	sec
	sbc     #$32
	sta     _Player1+4
	jcs     L0263
	dec     _Player1+4+1
;
; else if (Player1.vel_x > 0)
;
	jmp     L0263
L0227:	lda     _Player1+4
	cmp     #$01
	lda     _Player1+4+1
	sbc     #$00
	bvs     L0230
	eor     #$80
L0230:	bpl     L022E
;
; Player1.vel_x = 0;
;
	ldx     #$00
	txa
;
; else
;
	jmp     L131A
;
; Player1.vel_x -= ACCEL;
;
L022E:	lda     _Player1+4
	sec
	sbc     #$1E
	sta     _Player1+4
	bcs     L0236
	dec     _Player1+4+1
;
; if (Player1.vel_x < -MAX_SPEED)
;
L0236:	lda     _Player1+4
	cmp     #$A0
	lda     _Player1+4+1
	sbc     #$FE
	bvc     L0239
	eor     #$80
L0239:	jpl     L0263
;
; Player1.vel_x = -MAX_SPEED;
;
	ldx     #$FE
	lda     #$A0
;
; else if (pad1 & PAD_RIGHT)
;
	jmp     L131A
L1318:	lda     _pad1
	and     #$01
	beq     L023D
;
; direction = RIGHT;
;
	lda     #$01
	sta     _direction
;
; if (Player1.vel_x <= DECEL)
;
	lda     _Player1+4
	cmp     #$33
	lda     _Player1+4+1
	sbc     #$00
	bvc     L0243
	eor     #$80
L0243:	bpl     L0241
;
; Player1.vel_x += DECEL;
;
	lda     #$32
	clc
	adc     _Player1+4
	sta     _Player1+4
	jcc     L0263
	inc     _Player1+4+1
;
; else if (Player1.vel_x < 0)
;
	jmp     L0263
L0241:	ldx     _Player1+4+1
	cpx     #$80
	bcc     L0248
;
; Player1.vel_x = 0;
;
	ldx     #$00
	txa
;
; else
;
	jmp     L131A
;
; Player1.vel_x += ACCEL;
;
L0248:	lda     #$1E
	clc
	adc     _Player1+4
	sta     _Player1+4
	bcc     L024F
	inc     _Player1+4+1
;
; if (Player1.vel_x >= MAX_SPEED)
;
L024F:	lda     _Player1+4
	cmp     #$60
	lda     _Player1+4+1
	sbc     #$01
	bvs     L0252
	eor     #$80
L0252:	bpl     L0263
;
; Player1.vel_x = MAX_SPEED;
;
	ldx     #$01
	lda     #$60
;
; else
;
	jmp     L131A
;
; if (Player1.vel_x >= ACCEL)
;
L023D:	lda     _Player1+4
	cmp     #$1E
	lda     _Player1+4+1
	sbc     #$00
	bvs     L0258
	eor     #$80
L0258:	bpl     L0256
;
; Player1.vel_x -= ACCEL;
;
	lda     _Player1+4
	sec
	sbc     #$1E
	sta     _Player1+4
	bcs     L0263
	dec     _Player1+4+1
;
; else if (Player1.vel_x < -ACCEL)
;
	jmp     L0263
L0256:	lda     _Player1+4
	cmp     #$E2
	lda     _Player1+4+1
	sbc     #$FF
	bvc     L025F
	eor     #$80
L025F:	asl     a
	lda     #$00
	tax
	bcc     L131A
;
; Player1.vel_x += ACCEL;
;
	lda     #$1E
	clc
	adc     _Player1+4
	sta     _Player1+4
	bcc     L0263
	inc     _Player1+4+1
;
; else
;
	jmp     L0263
;
; Player1.vel_x = 0;
;
L131A:	sta     _Player1+4
	stx     _Player1+4+1
;
; Player1.x += Player1.vel_x;
;
L0263:	lda     _Player1+4
	clc
	adc     _Player1
	sta     _Player1
	lda     _Player1+4+1
	adc     _Player1+1
	sta     _Player1+1
;
; if (Player1.vel_y < 0x300)
;
	lda     _Player1+6
	cmp     #$00
	lda     _Player1+6+1
	sbc     #$03
	bvc     L026A
	eor     #$80
L026A:	bpl     L0268
;
; Player1.vel_y += GRAVITY;
;
	lda     #$3C
	clc
	adc     _Player1+6
	sta     _Player1+6
	bcc     L026E
	inc     _Player1+6+1
;
; else
;
	jmp     L026E
;
; Player1.vel_y = 0x300; // consistent gravity
;
L0268:	ldx     #$03
	lda     #$00
	sta     _Player1+6
	stx     _Player1+6+1
;
; if (pad1 & PAD_A)
;
L026E:	lda     _pad1
	and     #$80
	beq     L0271
;
; Player1.vel_y = JUMP_VEL; // JUMP
;
	ldx     #$FD
	lda     #$F0
	sta     _Player1+6
	stx     _Player1+6+1
;
; Player1.y += Player1.vel_y; // add gravity to y; (make him go up or down)
;
L0271:	lda     _Player1+6
	clc
	adc     _Player1+2
	sta     _Player1+2
	lda     _Player1+6+1
	adc     _Player1+2+1
	sta     _Player1+2+1
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ check_player_colision (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_check_player_colision: near

.segment	"BANK0"

;
; Generic.x = high_byte(Player1.x); // this is much faster than passing a pointer
;
	lda     _Player1+1
	sta     _Generic
;
; Generic.y = high_byte(Player1.y);
;
	lda     _Player1+3
	sta     _Generic+1
;
; Generic.width = HERO_WIDTH;
;
	lda     #$0B
	sta     _Generic+2
;
; Generic.height = HERO_HEIGHT; 
;
	lda     #$14
	sta     _Generic+3
;
; if (Player1.vel_x < 0)
;
	ldx     _Player1+4+1
	cpx     #$80
	bcc     L0282
;
; if (bg_coll_L())
;
	jsr     _bg_coll_L
	tax
	beq     L029C
;
; high_byte(Player1.x) = high_byte(Player1.x) - eject_L;
;
	lda     _Player1+1
	sec
	sbc     _eject_L
	sta     _Player1+1
;
; Player1.vel_x = 0;
;
	lda     #$00
	sta     _Player1+4
	sta     _Player1+4+1
;
; if (Player1.x > 0xf000)
;
	lda     _Player1
	cmp     #$01
	lda     _Player1+1
	sbc     #$F0
	bcc     L029C
;
; Player1.x = 0xf000;
;
	ldx     #$F0
;
; else if (Player1.vel_x > 0)
;
	jmp     L131F
L0282:	lda     _Player1+4
	cmp     #$01
	lda     _Player1+4+1
	sbc     #$00
	bvs     L0293
	eor     #$80
L0293:	bpl     L029C
;
; if (bg_coll_R())
;
	jsr     _bg_coll_R
	tax
	beq     L029C
;
; high_byte(Player1.x) = high_byte(Player1.x) - eject_R;
;
	lda     _Player1+1
	sec
	sbc     _eject_R
	sta     _Player1+1
;
; Player1.vel_x = 0;
;
	lda     #$00
	sta     _Player1+4
	sta     _Player1+4+1
;
; if (Player1.x > 0xf000)
;
	lda     _Player1
	cmp     #$01
	lda     _Player1+1
	sbc     #$F0
	bcc     L029C
;
; Player1.x = 0x0000;
;
	ldx     #$00
L131F:	lda     #$00
	sta     _Player1
	stx     _Player1+1
;
; if (Player1.y > 0xf000)   // limit how high he can go
;
L029C:	lda     _Player1+2
	cmp     #$01
	lda     _Player1+2+1
	sbc     #$F0
	bcc     L02A0
;
; Player1.y = 0x0000;
;
	lda     #$00
	sta     _Player1+2
	sta     _Player1+2+1
;
; if (Player1.vel_y > 0) // he's going down
;
L02A0:	lda     _Player1+6
	cmp     #$01
	lda     _Player1+6+1
	sbc     #$00
	bvs     L02A6
	eor     #$80
L02A6:	bpl     L02A4
;
; if (bg_coll_D()) // if he's collising below
;
	jsr     _bg_coll_D
	tax
	beq     L02B9
;
; Player1.on_ground = 1;
;
	lda     #$01
	sta     _Player1+9
;
; high_byte(Player1.y) = high_byte(Player1.y) - eject_D;
;
	lda     _Player1+3
	sec
	sbc     _eject_D
	sta     _Player1+3
;
; Player1.y &= 0xff00;
;
	ldx     _Player1+2+1
	lda     #$00
	sta     _Player1+2
	stx     _Player1+2+1
;
; if (Player1.vel_y > 0)
;
	lda     _Player1+6
	cmp     #$01
	lda     _Player1+6+1
	sbc     #$00
	bvs     L02B3
	eor     #$80
L02B3:	bpl     L02B9
;
; else if (Player1.vel_y < 0) // he's going up
;
	jmp     L1320
L02A4:	ldx     _Player1+6+1
	cpx     #$80
	bcc     L02B9
;
; if (bg_coll_U())
;
	jsr     _bg_coll_U
	tax
	beq     L02B9
;
; high_byte(Player1.y) = high_byte(Player1.y) - eject_U;
;
	lda     _Player1+3
	sec
	sbc     _eject_U
	sta     _Player1+3
;
; Player1.vel_y = 0;
;
L1320:	lda     #$00
	sta     _Player1+6
	sta     _Player1+6+1
;
; }
;
L02B9:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ bank0_player_movement (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bank0_player_movement: near

.segment	"BANK0"

;
; move_player();
;
	jsr     _move_player
;
; check_player_colision();
;
	jmp     _check_player_colision

.endproc

; ---------------------------------------------------------------
; void __near__ bank0_draw_player_sprite (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bank0_draw_player_sprite: near

.segment	"BANK0"

;
; temp_x = Player1.x >> 8;
;
	ldx     #$00
	lda     _Player1+1
	sta     _temp_x
	stx     _temp_x+1
;
; temp_y = Player1.y >> 8; 
;
	lda     _Player1+3
	sta     _temp_y
	stx     _temp_y+1
;
; temp_sprite = noah_box;  
;
	lda     #>(_noah_box)
	sta     _temp_sprite+1
	lda     #<(_noah_box)
	sta     _temp_sprite
;
; oam_meta_spr(temp_x, temp_y, temp_sprite);
;
	jsr     decsp2
	lda     _temp_x
	ldy     #$01
	sta     (sp),y
	lda     _temp_y
	dey
	sta     (sp),y
	lda     _temp_sprite
	ldx     _temp_sprite+1
	jmp     _oam_meta_spr

.endproc

; ---------------------------------------------------------------
; void __near__ function_bank1 (void)
; ---------------------------------------------------------------

.segment	"BANK1"

.proc	_function_bank1: near

.segment	"BANK1"

;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ function_bank2 (void)
; ---------------------------------------------------------------

.segment	"BANK2"

.proc	_function_bank2: near

.segment	"BANK2"

;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ drawMetatileBlock (void)
; ---------------------------------------------------------------

.segment	"BANK2"

.proc	_drawMetatileBlock: near

.segment	"BANK2"

;
; address = get_ppu_addr(nt, x, temp2);
;
	jsr     decsp2
	lda     _nt
	ldy     #$01
	sta     (sp),y
	lda     _x
	dey
	sta     (sp),y
	lda     _temp2
	jsr     _get_ppu_addr
	sta     _address
	stx     _address+1
;
; index = temp2 + (x >> 4);
;
	lda     _x
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	clc
	adc     _temp2
	sta     _index
	lda     #$00
	adc     _temp2+1
;
; buffer_4_mt(address, index); // ppu_address, index to the data
;
	lda     _address
	ldx     _address+1
	jsr     pushax
	lda     _index
	jmp     _buffer_4_mt

.endproc

; ---------------------------------------------------------------
; void __near__ draw_screen (void)
; ---------------------------------------------------------------

.segment	"BANK2"

.proc	_draw_screen: near

.segment	"BANK2"

;
; offset = current_level;
;
	lda     _current_level
	sta     _offset
;
; offset += (pseudo_scroll_x >> 8); // high byte of pseudo_scroll_x
;
	lda     _pseudo_scroll_x+1
	clc
	adc     _offset
	sta     _offset
;
; if (offset >= levels_per_stage[current_stage]) {
;
	lda     _offset
	jsr     pusha0
	ldy     _current_stage
	lda     _levels_per_stage,y
	jsr     tosicmp0
	bcc     L110B
;
; offset = current_level;
;
	lda     _current_level
	sta     _offset
;
; if (Player1.vel_x < 0)
;
L110B:	ldx     _Player1+4+1
	cpx     #$80
	ldx     #$00
	bcc     L1326
;
; offset -= 1;
;
	dec     _offset
;
; set_data_pointer(stage_table[current_stage][offset]);
;
L1326:	lda     _current_stage
	asl     a
	bcc     L1324
	inx
	clc
L1324:	adc     #<(_stage_table)
	sta     ptr1
	txa
	adc     #>(_stage_table)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     _offset
	asl     a
	bcc     L1325
	inx
	clc
L1325:	adc     ptr1
	sta     ptr1
	txa
	adc     ptr1+1
	sta     ptr1+1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _set_data_pointer
;
; nt = ((pseudo_scroll_x >> 8) & 1);
;
	lda     _pseudo_scroll_x+1
	and     #$01
	sta     _nt
;
; x = pseudo_scroll_x & 0xff;
;
	lda     _pseudo_scroll_x
	sta     _x
;
; switch (scroll_count)
;
	ldx     #$00
	lda     _scroll_count
;
; }
;
	beq     L1328
	cmp     #$01
	beq     L1329
	cmp     #$02
	beq     L132A
	jmp     L132B
;
; temp2 = 0;
;
L1328:	sta     _temp2
	sta     _temp2+1
;
; drawMetatileBlock();
;
	jsr     _drawMetatileBlock
;
; temp2 = 0x20;
;
	ldx     #$00
	lda     #$20
;
; break;
;
	jmp     L132D
;
; temp2 = 0x40;
;
L1329:	lda     #$40
	sta     _temp2
	stx     _temp2+1
;
; drawMetatileBlock();
;
	jsr     _drawMetatileBlock
;
; temp2 = 0x60;
;
	ldx     #$00
	lda     #$60
;
; break;
;
	jmp     L132D
;
; temp2 = 0x80;
;
L132A:	lda     #$80
	sta     _temp2
	stx     _temp2+1
;
; drawMetatileBlock();
;
	jsr     _drawMetatileBlock
;
; temp2 = 0xa0;
;
	ldx     #$00
	lda     #$A0
;
; break;
;
	jmp     L132D
;
; temp2 = 0xc0;
;
L132B:	lda     #$C0
	sta     _temp2
	stx     _temp2+1
;
; drawMetatileBlock();
;
	jsr     _drawMetatileBlock
;
; temp2 = 0xe0;
;
	ldx     #$00
	lda     #$E0
L132D:	sta     _temp2
	stx     _temp2+1
;
; drawMetatileBlock();
;
	jsr     _drawMetatileBlock
;
; ++scroll_count;   // Reverse the increment to scroll in the opposite direction
;
	inc     _scroll_count
;
; scroll_count &= 3; // mask off top bits, keep it 0-3
;
	lda     _scroll_count
	and     #$03
	sta     _scroll_count
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ new_cmap (void)
; ---------------------------------------------------------------

.segment	"BANK2"

.proc	_new_cmap: near

.segment	"BANK2"

;
; offset = room_to_load;
;
	lda     _room_to_load
	sta     _offset
;
; map = room_to_load & 1; // even or odd?
;
	lda     _room_to_load
	and     #$01
	sta     _map
;
; if (!map) 
;
	lda     _map
	jne     L1149
;
; memcpy(c_map, stage_table[current_stage][offset], 240); 
;
	lda     #<(_c_map)
	ldx     #>(_c_map)
	jsr     pushax
	ldx     #$00
	lda     _current_stage
	asl     a
	bcc     L1336
	inx
	clc
L1336:	adc     #<(_stage_table)
	sta     ptr1
	txa
	adc     #>(_stage_table)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     _offset
	asl     a
	bcc     L1337
	inx
	clc
L1337:	adc     ptr1
	sta     ptr1
	txa
	adc     ptr1+1
	sta     ptr1+1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldx     #$00
	lda     #$F0
	jsr     _memcpy
;
; if (scrolling_direction) 
;
	lda     _scrolling_direction
	beq     L1151
;
; if (offset + 1 < levels_per_stage[current_stage])
;
	ldx     #$00
	lda     _offset
	clc
	adc     #$01
	bcc     L1155
	inx
L1155:	jsr     pushax
	ldy     _current_stage
	lda     _levels_per_stage,y
	jsr     tosicmp0
	bcc     L133E
;
; else
;
	rts
;
; memcpy(c_map2, stage_table[current_stage][offset + 1], 240);
;
L133E:	lda     #<(_c_map2)
	ldx     #>(_c_map2)
	jsr     pushax
	ldx     #$00
	lda     _current_stage
	asl     a
	bcc     L1338
	inx
	clc
L1338:	adc     #<(_stage_table)
	sta     ptr1
	txa
	adc     #>(_stage_table)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     _offset
	clc
	adc     #$01
	bcc     L115D
	inx
L115D:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     ptr1
	sta     ptr1
	lda     tmp1
	adc     ptr1+1
	sta     ptr1+1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldx     #$00
	lda     #$F0
	jmp     _memcpy
;
; if (offset - 1 >= 0)
;
L1151:	lda     _offset
	sec
	sbc     #$01
	jsr     return1
	bne     L133F
;
; }
;
	rts
;
; memcpy(c_map2, stage_table[current_stage][offset - 1], 240);
;
L133F:	lda     #<(_c_map2)
	ldx     #>(_c_map2)
	jsr     pushax
	ldx     #$00
	lda     _current_stage
	asl     a
	bcc     L1339
	inx
	clc
L1339:	adc     #<(_stage_table)
	sta     ptr1
	txa
	adc     #>(_stage_table)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     _offset
	sec
	sbc     #$01
	bcs     L1168
	dex
L1168:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     ptr1
	sta     ptr1
	lda     tmp1
	adc     ptr1+1
	sta     ptr1+1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldx     #$00
	lda     #$F0
	jmp     _memcpy
;
; memcpy(c_map2, stage_table[current_stage][offset], 240);
;
L1149:	lda     #<(_c_map2)
	ldx     #>(_c_map2)
	jsr     pushax
	ldx     #$00
	lda     _current_stage
	asl     a
	bcc     L133A
	inx
	clc
L133A:	adc     #<(_stage_table)
	sta     ptr1
	txa
	adc     #>(_stage_table)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     _offset
	asl     a
	bcc     L133B
	inx
	clc
L133B:	adc     ptr1
	sta     ptr1
	txa
	adc     ptr1+1
	sta     ptr1+1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldx     #$00
	lda     #$F0
	jsr     _memcpy
;
; if (scrolling_direction)
;
	lda     _scrolling_direction
	beq     L1171
;
; if (offset + 1 < levels_per_stage[current_stage])
;
	ldx     #$00
	lda     _offset
	clc
	adc     #$01
	bcc     L1175
	inx
L1175:	jsr     pushax
	ldy     _current_stage
	lda     _levels_per_stage,y
	jsr     tosicmp0
	bcc     L1340
;
; }
;
	rts
;
; memcpy(c_map, stage_table[current_stage][offset + 1], 240);
;
L1340:	lda     #<(_c_map)
	ldx     #>(_c_map)
	jsr     pushax
	ldx     #$00
	lda     _current_stage
	asl     a
	bcc     L133C
	inx
	clc
L133C:	adc     #<(_stage_table)
	sta     ptr1
	txa
	adc     #>(_stage_table)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     _offset
	clc
	adc     #$01
	bcc     L117D
	inx
L117D:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     ptr1
	sta     ptr1
	lda     tmp1
	adc     ptr1+1
	sta     ptr1+1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldx     #$00
	lda     #$F0
	jmp     _memcpy
;
; if (offset - 1 >= 0)
;
L1171:	lda     _offset
	sec
	sbc     #$01
	jsr     return1
	beq     L1180
;
; memcpy(c_map, stage_table[current_stage][offset - 1], 240);
;
	lda     #<(_c_map)
	ldx     #>(_c_map)
	jsr     pushax
	ldx     #$00
	lda     _current_stage
	asl     a
	bcc     L133D
	inx
	clc
L133D:	adc     #<(_stage_table)
	sta     ptr1
	txa
	adc     #>(_stage_table)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     _offset
	sec
	sbc     #$01
	bcs     L1188
	dex
L1188:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     ptr1
	sta     ptr1
	lda     tmp1
	adc     ptr1+1
	sta     ptr1+1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldx     #$00
	lda     #$F0
	jmp     _memcpy
;
; }
;
L1180:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ prep_scroll_screen (void)
; ---------------------------------------------------------------

.segment	"BANK2"

.proc	_prep_scroll_screen: near

.segment	"BANK2"

;
; temp1 = low_byte(scroll_x) + high_byte(Player1.x);
;
	ldx     #$00
	lda     _scroll_x
	clc
	adc     _Player1+1
	bcc     L1341
	inx
L1341:	sta     _temp1
	stx     _temp1+1
;
; if (temp1 > 0x98 && temp1 < 0xa4) // middle of the screen
;
	cmp     #$99
	txa
	sbc     #$00
	bcc     L118F
	lda     _temp1+1
	cmp     #$00
	bne     L1192
	lda     _temp1
	cmp     #$A4
L1192:	bcs     L118F
;
; map_loaded = 0;
;
	lda     #$00
	sta     _map_loaded
;
; temp2 = Player1.x; // store his x before we check the scrolling
;
L118F:	lda     _Player1+1
	sta     _temp2+1
	lda     _Player1
	sta     _temp2
;
; if (Player1.x < MAX_LEFT)
;
	ldx     _Player1+1
	cpx     #$50
	jcs     L11C1
;
; if (!map_loaded)
;
	lda     _map_loaded
	bne     L119A
;
; room_to_load = ((scroll_x >> 8) - 1); // high byte = room, one to the left
;
	lda     _scroll_x+1
	sec
	sbc     #$01
	sta     _room_to_load
;
; new_cmap();
;
	jsr     _new_cmap
;
; map_loaded = 1; // only do once
;
	lda     #$01
	sta     _map_loaded
;
; temp1 = (MAX_LEFT - Player1.x) >> 8;
;
L119A:	lda     #$00
	sec
	sbc     _Player1
	lda     #$50
	sbc     _Player1+1
	ldx     #$00
	sta     _temp1
	stx     _temp1+1
;
; if (temp1 > 3)
;
	cmp     #$04
	bcc     L11A7
;
; temp1 = 3; // max scroll change
;
	lda     #$03
	sta     _temp1
	stx     _temp1+1
;
; temp3 = scroll_x + high_byte(Player1.x);
;
L11A7:	lda     _scroll_x
	ldx     _scroll_x+1
	clc
	adc     _Player1+1
	bcc     L1342
	inx
L1342:	sta     _temp3
	stx     _temp3+1
;
; current_level = (temp3 >> 8);
;
	lda     _temp3+1
	sta     _current_level
;
; max_rooms = levels_per_stage[current_stage] - 1;
;
	ldy     _current_stage
	lda     _levels_per_stage,y
	sec
	sbc     #$01
	sta     _max_rooms
;
; max_scroll = (max_rooms * 0x100) - 1;
;
	tax
	lda     #$00
	sec
	sbc     #$01
	bcs     L11B9
	dex
L11B9:	sta     _max_scroll
	stx     _max_scroll+1
;
; if (max_rooms >= 1) // this is for the multi-room levels
;
	lda     _max_rooms
	beq     L11C1
;
; if ((scroll_x - temp1) > max_scroll) // if subtracting the scroll makes it overflow
;
	lda     _scroll_x
	sec
	sbc     _temp1
	pha
	lda     _scroll_x+1
	sbc     _temp1+1
	tax
	pla
	sec
	sbc     _max_scroll
	sta     tmp1
	txa
	sbc     _max_scroll+1
	ora     tmp1
	bcc     L11BC
	beq     L11BC
;
; scroll_x = 0; // just go to zero (and move the guy)
;
	lda     #$00
	sta     _scroll_x
	sta     _scroll_x+1
;
; else // otherwise scroll the window and offset the guy's movement
;
	jmp     L11C1
;
; scroll_x -= temp1;                  // scroll the window
;
L11BC:	lda     _temp1
	eor     #$FF
	sec
	adc     _scroll_x
	sta     _scroll_x
	lda     _temp1+1
	eor     #$FF
	adc     _scroll_x+1
	sta     _scroll_x+1
;
; high_byte(Player1.x) = high_byte(Player1.x) + temp1; // add the offset to the guy
;
	lda     _Player1+1
	clc
	adc     _temp1
	sta     _Player1+1
	lda     #$00
	adc     _temp1+1
;
; if (Player1.x > MAX_RIGHT)
;
L11C1:	lda     _Player1
	cmp     #$01
	lda     _Player1+1
	sbc     #$90
	bcc     L11DB
;
; if (!map_loaded) // gets reset whenever the player's in the middle of the level
;
	lda     _map_loaded
	bne     L11CA
;
; room_to_load = ((scroll_x >> 8) + 1); // high byte = room, one to the left
;
	lda     _scroll_x+1
	clc
	adc     #$01
	sta     _room_to_load
;
; new_cmap();
;
	jsr     _new_cmap
;
; map_loaded = 1; // only do once
;
	lda     #$01
	sta     _map_loaded
;
; temp1 = (Player1.x - MAX_RIGHT) >> 8;
;
L11CA:	lda     _Player1+1
	sec
	sbc     #$90
	ldx     #$00
	sta     _temp1
	stx     _temp1+1
;
; if (temp1 > 3)
;
	cmp     #$04
	bcc     L1346
;
; temp1 = 3; // max scroll change
;
	lda     #$03
	sta     _temp1
	stx     _temp1+1
;
; if (max_rooms >= 1) // used for single room levels
;
L1346:	lda     _max_rooms
	beq     L11DB
;
; scroll_x += temp1;                  // scroll the window
;
	lda     _temp1
	clc
	adc     _scroll_x
	sta     _scroll_x
	lda     _temp1+1
	adc     _scroll_x+1
	sta     _scroll_x+1
;
; high_byte(Player1.x) = high_byte(Player1.x) - temp1; // sub the offet from the guy
;
	lda     _Player1+1
	sec
	sbc     _temp1
	sta     _Player1+1
	txa
	sbc     _temp1+1
;
; if (scroll_x >= max_scroll)
;
L11DB:	lda     _scroll_x
	cmp     _max_scroll
	lda     _scroll_x+1
	sbc     _max_scroll+1
	bcc     L11E9
;
; scroll_x = max_scroll;      // stop scrolling right, end of level
;
	lda     _max_scroll+1
	sta     _scroll_x+1
	lda     _max_scroll
	sta     _scroll_x
;
; Player1.x = temp2;        // but allow the x position to go all the way right
;
	lda     _temp2+1
	sta     _Player1+1
	lda     _temp2
	sta     _Player1
;
; if (high_byte(Player1.x) >= 0xe0) // but limit how far right he can go
;
	lda     _Player1+1
	cmp     #$E0
	bcc     L11E9
;
; Player1.x = 0xe000;
;
	ldx     #$E0
	lda     #$00
	sta     _Player1
	stx     _Player1+1
;
; }
;
L11E9:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ handle_scrolling (void)
; ---------------------------------------------------------------

.segment	"BANK2"

.proc	_handle_scrolling: near

.segment	"BANK2"

;
; scrolling_direction = (Player1.vel_x >= 0) ? 0 : 1;
;
	ldx     _Player1+4+1
	bmi     L11F2
	lda     #$00
	jmp     L1347
L11F2:	lda     #$01
L1347:	sta     _scrolling_direction
;
; if (!r_scroll_frames && !l_scroll_frames)
;
	lda     _r_scroll_frames
	bne     L11FF
	lda     _l_scroll_frames
	bne     L11FF
;
; if (Player1.vel_x > 0)
;
	lda     _Player1+4
	cmp     #$01
	lda     _Player1+4+1
	sbc     #$00
	bvs     L11FC
	eor     #$80
L11FC:	bpl     L134A
;
; r_scroll_frames = 4;
;
	lda     #$04
	sta     _r_scroll_frames
;
; else
;
	jmp     L11FF
;
; l_scroll_frames = 4;
;
L134A:	lda     #$04
	sta     _l_scroll_frames
;
; if (r_scroll_frames)
;
L11FF:	lda     _r_scroll_frames
	beq     L1202
;
; pseudo_scroll_x = scroll_x + 0x120;
;
	lda     _scroll_x
	ldx     _scroll_x+1
	clc
	adc     #$20
	bcc     L1206
	inx
L1206:	inx
	sta     _pseudo_scroll_x
	stx     _pseudo_scroll_x+1
;
; draw_screen();
;
	jsr     _draw_screen
;
; --r_scroll_frames;
;
	dec     _r_scroll_frames
;
; else if (l_scroll_frames)
;
	rts
L1202:	lda     _l_scroll_frames
	beq     L120A
;
; pseudo_scroll_x = scroll_x - 0x20; 
;
	lda     _scroll_x
	ldx     _scroll_x+1
	sec
	sbc     #$20
	bcs     L120E
	dex
L120E:	sta     _pseudo_scroll_x
	stx     _pseudo_scroll_x+1
;
; draw_screen();
;
	jsr     _draw_screen
;
; --l_scroll_frames;
;
	dec     _l_scroll_frames
;
; }
;
L120A:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ bank2_load_room (void)
; ---------------------------------------------------------------

.segment	"BANK2"

.proc	_bank2_load_room: near

.segment	"BANK2"

;
; clear_vram_buffer();
;
	jsr     _clear_vram_buffer
;
; set_data_pointer(stage_table[current_stage][current_level]);
;
	ldx     #$00
	lda     _current_stage
	asl     a
	bcc     L1358
	inx
	clc
L1358:	adc     #<(_stage_table)
	sta     ptr1
	txa
	adc     #>(_stage_table)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     _current_level
	asl     a
	bcc     L1359
	inx
	clc
L1359:	adc     ptr1
	sta     ptr1
	txa
	adc     ptr1+1
	sta     ptr1+1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _set_data_pointer
;
; set_mt_pointer(metatile);
;
	lda     #<(_metatile)
	ldx     #>(_metatile)
	jsr     _set_mt_pointer
;
; for (y = 0;; y += 0x20)
;
	lda     #$00
L1355:	sta     _y
;
; for (x = 0;; x += 0x20)
;
	lda     #$00
L1354:	sta     _x
;
; address = get_ppu_addr(nametable_to_load, x, y);
;
	jsr     decsp2
	lda     _nametable_to_load
	ldy     #$01
	sta     (sp),y
	lda     _x
	dey
	sta     (sp),y
	lda     _y
	jsr     _get_ppu_addr
	sta     _address
	stx     _address+1
;
; index = (y & 0xf0) + (x >> 4);
;
	lda     _y
	and     #$F0
	sta     ptr1
	lda     _x
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	clc
	adc     ptr1
	sta     _index
;
; buffer_4_mt(address, index); // ppu_address, index to the data
;
	lda     _address
	ldx     _address+1
	jsr     pushax
	lda     _index
	jsr     _buffer_4_mt
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; if (x == 0xe0)
;
	ldx     #$00
	lda     _x
	cmp     #$E0
;
; break;
;
	beq     L135F
;
; for (x = 0;; x += 0x20)
;
	lda     #$20
	clc
	adc     _x
	jmp     L1354
;
; if (y == 0xe0)
;
L135F:	lda     _y
	cmp     #$E0
;
; break;
;
	beq     L1360
;
; for (y = 0;; y += 0x20)
;
	lda     #$20
	clc
	adc     _y
	jmp     L1355
;
; set_data_pointer(stage_table[current_stage][current_level+1]);
;
L1360:	lda     _current_stage
	asl     a
	bcc     L135A
	inx
	clc
L135A:	adc     #<(_stage_table)
	sta     ptr1
	txa
	adc     #>(_stage_table)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     _current_level
	clc
	adc     #$01
	bcc     L123E
	inx
L123E:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     ptr1
	sta     ptr1
	lda     tmp1
	adc     ptr1+1
	sta     ptr1+1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _set_data_pointer
;
; for (y = 0;; y += 0x20)
;
	lda     #$00
L1356:	sta     _y
;
; x = 0;
;
	lda     #$00
	sta     _x
;
; nt = (nametable_to_load + 1) % 2;
;
	lda     _nametable_to_load
	clc
	adc     #$01
	and     #$01
	sta     _nt
;
; address = get_ppu_addr(1, x, y);
;
	jsr     decsp2
	lda     #$01
	tay
	sta     (sp),y
	lda     _x
	dey
	sta     (sp),y
	lda     _y
	jsr     _get_ppu_addr
	sta     _address
	stx     _address+1
;
; index = (y & 0xf0);
;
	lda     _y
	and     #$F0
	sta     _index
;
; buffer_4_mt(address, index); // ppu_address, index to the data
;
	lda     _address
	ldx     _address+1
	jsr     pushax
	lda     _index
	jsr     _buffer_4_mt
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; if (y == 0xe0)
;
	lda     _y
	cmp     #$E0
;
; break;
;
	beq     L1361
;
; for (y = 0;; y += 0x20)
;
	lda     #$20
	clc
	adc     _y
	jmp     L1356
;
; if (current_level > 0) {
;
L1361:	lda     _current_level
	jeq     L1263
;
; set_data_pointer(stage_table[current_stage][current_level-1]);
;
	ldx     #$00
	lda     _current_stage
	asl     a
	bcc     L135B
	inx
	clc
L135B:	adc     #<(_stage_table)
	sta     ptr1
	txa
	adc     #>(_stage_table)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     _current_level
	sec
	sbc     #$01
	bcs     L1261
	dex
L1261:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     ptr1
	sta     ptr1
	lda     tmp1
	adc     ptr1+1
	sta     ptr1+1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _set_data_pointer
;
; for (y = 0;; y += 0x20)
;
	lda     #$00
L1357:	sta     _y
;
; x = 240;
;
	lda     #$F0
	sta     _x
;
; nt = nametable_to_load;
;
	lda     _nametable_to_load
	sta     _nt
;
; address = get_ppu_addr(nt, x, y);
;
	jsr     decsp2
	lda     _nt
	ldy     #$01
	sta     (sp),y
	lda     _x
	dey
	sta     (sp),y
	lda     _y
	jsr     _get_ppu_addr
	sta     _address
	stx     _address+1
;
; index = y + (x >> 4);
;
	lda     _x
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	clc
	adc     _y
	sta     _index
;
; buffer_4_mt(address, index); // ppu_address, index to the data
;
	lda     _address
	ldx     _address+1
	jsr     pushax
	lda     _index
	jsr     _buffer_4_mt
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; if (y == 0xe0)
;
	lda     _y
	cmp     #$E0
;
; break;
;
	beq     L1263
;
; for (y = 0;; y += 0x20)
;
	lda     #$20
	clc
	adc     _y
	jmp     L1357
;
; memcpy(c_map, stage_table[current_stage][current_level], 240); 
;
L1263:	lda     #<(_c_map)
	ldx     #>(_c_map)
	jsr     pushax
	ldx     #$00
	lda     _current_stage
	asl     a
	bcc     L135C
	inx
	clc
L135C:	adc     #<(_stage_table)
	sta     ptr1
	txa
	adc     #>(_stage_table)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     _current_level
	asl     a
	bcc     L135D
	inx
	clc
L135D:	adc     ptr1
	sta     ptr1
	txa
	adc     ptr1+1
	sta     ptr1+1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldx     #$00
	lda     #$F0
	jsr     _memcpy
;
; if (current_level + 1 < levels_per_stage[current_stage]) {
;
	ldx     #$00
	lda     _current_level
	clc
	adc     #$01
	bcc     L1284
	inx
L1284:	jsr     pushax
	ldy     _current_stage
	lda     _levels_per_stage,y
	jsr     tosicmp0
	bcs     L1282
;
; memcpy(c_map2, stage_table[current_stage][current_level + 1], 240);
;
	lda     #<(_c_map2)
	ldx     #>(_c_map2)
	jsr     pushax
	ldx     #$00
	lda     _current_stage
	asl     a
	bcc     L135E
	inx
	clc
L135E:	adc     #<(_stage_table)
	sta     ptr1
	txa
	adc     #>(_stage_table)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     _current_level
	clc
	adc     #$01
	bcc     L128C
	inx
L128C:	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     ptr1
	sta     ptr1
	lda     tmp1
	adc     ptr1+1
	sta     ptr1+1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldx     #$00
	lda     #$F0
	jsr     _memcpy
;
; map_loaded = 1;
;
L1282:	lda     #$01
	sta     _map_loaded
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ bank2_scroll_screen (void)
; ---------------------------------------------------------------

.segment	"BANK2"

.proc	_bank2_scroll_screen: near

.segment	"BANK2"

;
; prep_scroll_screen();
;
	jsr     _prep_scroll_screen
;
; set_scroll_x(scroll_x);
;
	lda     _scroll_x
	ldx     _scroll_x+1
	jsr     _set_scroll_x
;
; handle_scrolling();
;
	jmp     _handle_scrolling

.endproc

; ---------------------------------------------------------------
; void __near__ function_bank3 (void)
; ---------------------------------------------------------------

.segment	"BANK3"

.proc	_function_bank3: near

.segment	"BANK3"

;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ function_bank4 (void)
; ---------------------------------------------------------------

.segment	"BANK4"

.proc	_function_bank4: near

.segment	"BANK4"

;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ function_bank5 (void)
; ---------------------------------------------------------------

.segment	"BANK5"

.proc	_function_bank5: near

.segment	"BANK5"

;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ function_bank6 (void)
; ---------------------------------------------------------------

.segment	"BANK6"

.proc	_function_bank6: near

.segment	"BANK6"

;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; bank_spr(0);
;
	lda     #$00
	jsr     _bank_spr
;
; bank_bg(1);
;
	lda     #$01
	jsr     _bank_bg
;
; ppu_off();    // screen off
;
	jsr     _ppu_off
;
; pal_bg(palette_bg); // load the BG palette
;
	lda     #<(_palette_bg)
	ldx     #>(_palette_bg)
	jsr     _pal_bg
;
; pal_spr(palette_sp); // load the sprite palette
;
	lda     #<(_palette_sp)
	ldx     #>(_palette_sp)
	jsr     _pal_spr
;
; set_vram_buffer(); // do at least once 
;
	jsr     _set_vram_buffer
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; set_mirroring(MIRROR_VERTICAL);
;
	lda     #$02
	jsr     _set_mirroring
;
; nametable_to_load = 0; //todo: move this
;
	lda     #$00
	sta     _nametable_to_load
;
; current_level = 0;
;
	sta     _current_level
;
; current_stage = 0;  
;
	sta     _current_stage
;
; banked_call(BANK_2, bank2_load_room);   
;
	lda     #$02
	jsr     pusha
	lda     #<(_bank2_load_room)
	ldx     #>(_bank2_load_room)
	jsr     _banked_call
;
; ppu_on_all();   // turn on screen
;
	jsr     _ppu_on_all
;
; ppu_wait_nmi();      
;
L12DD:	jsr     _ppu_wait_nmi
;
; pad1 = pad_poll(0);  
;
	lda     #$00
	jsr     _pad_poll
	sta     _pad1
;
; pad1_new = get_pad_new(0);   
;
	lda     #$00
	jsr     _get_pad_new
	sta     _pad1_new
;
; if (pad1_new & PAD_START)   
;
	ldx     #$00
	and     #$10
	stx     tmp1
	ora     tmp1
;
; banked_call(BANK_0, bank0_player_movement);
;
	txa
	jsr     pusha
	lda     #<(_bank0_player_movement)
	ldx     #>(_bank0_player_movement)
	jsr     _banked_call
;
; banked_call(BANK_2, bank2_scroll_screen);  
;
	lda     #$02
	jsr     pusha
	lda     #<(_bank2_scroll_screen)
	ldx     #>(_bank2_scroll_screen)
	jsr     _banked_call
;
; oam_clear();  
;
	jsr     _oam_clear
;
; banked_call(BANK_0, bank0_draw_player_sprite);
;
	lda     #$00
	jsr     pusha
	lda     #<(_bank0_draw_player_sprite)
	ldx     #>(_bank0_draw_player_sprite)
	jsr     _banked_call
;
; while (1)      
;
	jmp     L12DD

.endproc

