;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_bg
	.import		_pal_spr
	.import		_ppu_wait_nmi
	.import		_ppu_off
	.import		_ppu_on_all
	.import		_oam_clear
	.import		_oam_meta_spr
	.import		_pad_poll
	.import		_bank_spr
	.import		_bank_bg
	.import		_memcpy
	.import		_set_vram_buffer
	.import		_clear_vram_buffer
	.import		_get_pad_new
	.import		_get_ppu_addr
	.import		_set_data_pointer
	.import		_set_mt_pointer
	.import		_buffer_4_mt
	.import		_flush_vram_update2
	.export		_bankLevel
	.export		_bankBuffer
	.export		_banked_call
	.export		_bank_push
	.export		_bank_pop
	.import		_set_prg_bank
	.import		_get_prg_bank
	.export		_direction
	.export		_direction_y
	.export		_arg1
	.export		_arg2
	.export		_pad1
	.export		_pad1_new
	.export		_char_state
	.export		_song
	.export		_sound
	.export		_temp_x
	.export		_temp_y
	.export		_temp_sprite
	.export		_old_x
	.export		_old_y
	.export		_eject_L
	.export		_eject_R
	.export		_eject_D
	.export		_eject_U
	.export		_collision_L
	.export		_collision_R
	.export		_collision_U
	.export		_collision_D
	.export		_coordinates
	.export		_location_with_scroll
	.export		_collision
	.export		_metatile_colision_map
	.export		_nametable_to_load
	.export		_level
	.export		_offset
	.export		_address
	.export		_x
	.export		_y
	.export		_nt
	.export		_index
	.export		_map
	.export		_scroll_x
	.export		_scroll_y
	.export		_max_rooms
	.export		_max_scroll
	.export		_room_to_load
	.export		_temp_room
	.export		_c_map
	.export		_c_map2
	.export		_Player1
	.export		_Generic
	.export		_Generic2
	.export		_wram_array
	.export		_noah_box
	.export		_topleft
	.export		_bottomleft
	.export		_bg_collision_sub
	.export		_bg_collision_fast
	.export		_bg_coll_L
	.export		_bg_coll_R
	.export		_bg_coll_ladder
	.export		_bg_coll_ladder_top_at_player
	.export		_bg_coll_ladder_top_under_player
	.export		_bg_coll_U
	.export		_bg_coll_D
	.export		_bg_coll_D2
	.export		_move_player
	.export		_check_player_colision
	.export		_bank0_player_movement
	.export		_bank0_draw_player_sprite
	.export		_function_bank1
	.export		_function_bank2
	.export		_level0_0
	.export		_metatile
	.export		_bank2_load_room
	.export		_function_bank3
	.export		_function_bank4
	.export		_function_bank5
	.export		_function_bank6
	.export		_palette_bg
	.export		_palette_sp
	.export		_main

.segment	"DATA"

_room_to_load:
	.byte	$00
_Player1:
	.word	$4000
	.word	$9400
	.res	5,$00

.segment	"RODATA"

_metatile_colision_map:
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$00
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
.segment	"BANK0"
_noah_box:
	.byte	$00
	.byte	$00
	.byte	$4F
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$4F
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$3F
	.byte	$80
	.byte	$06
	.byte	$00
	.byte	$4F
	.byte	$00
	.byte	$06
	.byte	$08
	.byte	$4F
	.byte	$00
	.byte	$06
	.byte	$10
	.byte	$3F
	.byte	$80
	.byte	$80
_topleft:
	.byte	$00
	.byte	$00
	.byte	$50
	.byte	$00
	.byte	$80
_bottomleft:
	.byte	$00
	.byte	$00
	.byte	$51
	.byte	$00
	.byte	$80
.segment	"BANK1"
.segment	"BANK2"
_level0_0:
	.byte	$3C
	.byte	$1E
	.byte	$1F
	.byte	$50
	.byte	$8B
	.byte	$86
	.byte	$2D
	.byte	$87
	.byte	$7B
	.byte	$86
	.byte	$2D
	.byte	$2D
	.byte	$92
	.byte	$94
	.byte	$89
	.byte	$94
	.byte	$00
	.byte	$01
	.byte	$1E
	.byte	$1F
	.byte	$86
	.byte	$93
	.byte	$2D
	.byte	$2D
	.byte	$87
	.byte	$93
	.byte	$2E
	.byte	$93
	.byte	$2D
	.byte	$2D
	.byte	$89
	.byte	$91
	.byte	$02
	.byte	$03
	.byte	$00
	.byte	$1E
	.byte	$93
	.byte	$92
	.byte	$2E
	.byte	$2D
	.byte	$92
	.byte	$91
	.byte	$2E
	.byte	$2E
	.byte	$93
	.byte	$2D
	.byte	$94
	.byte	$2D
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$91
	.byte	$93
	.byte	$2D
	.byte	$2D
	.byte	$2D
	.byte	$91
	.byte	$89
	.byte	$2D
	.byte	$2D
	.byte	$92
	.byte	$94
	.byte	$91
	.byte	$02
	.byte	$03
	.byte	$15
	.byte	$1B
	.byte	$91
	.byte	$2D
	.byte	$2D
	.byte	$2D
	.byte	$89
	.byte	$90
	.byte	$88
	.byte	$2E
	.byte	$2D
	.byte	$2E
	.byte	$88
	.byte	$91
	.byte	$00
	.byte	$15
	.byte	$CC
	.byte	$CD
	.byte	$29
	.byte	$89
	.byte	$2D
	.byte	$88
	.byte	$2A
	.byte	$46
	.byte	$90
	.byte	$2A
	.byte	$2B
	.byte	$2F
	.byte	$90
	.byte	$88
	.byte	$14
	.byte	$CE
	.byte	$BF
	.byte	$9A
	.byte	$49
	.byte	$90
	.byte	$2C
	.byte	$2A
	.byte	$47
	.byte	$73
	.byte	$48
	.byte	$49
	.byte	$6A
	.byte	$9F
	.byte	$49
	.byte	$2B
	.byte	$CA
	.byte	$C9
	.byte	$CD
	.byte	$50
	.byte	$50
	.byte	$49
	.byte	$62
	.byte	$48
	.byte	$50
	.byte	$71
	.byte	$77
	.byte	$50
	.byte	$69
	.byte	$50
	.byte	$50
	.byte	$9F
	.byte	$C9
	.byte	$CB
	.byte	$51
	.byte	$50
	.byte	$50
	.byte	$66
	.byte	$60
	.byte	$67
	.byte	$50
	.byte	$71
	.byte	$50
	.byte	$6E
	.byte	$69
	.byte	$50
	.byte	$50
	.byte	$76
	.byte	$C9
	.byte	$CB
	.byte	$CD
	.byte	$E2
	.byte	$59
	.byte	$59
	.byte	$61
	.byte	$58
	.byte	$59
	.byte	$72
	.byte	$58
	.byte	$59
	.byte	$68
	.byte	$58
	.byte	$59
	.byte	$58
	.byte	$C9
	.byte	$C9
	.byte	$CB
	.byte	$51
	.byte	$54
	.byte	$63
	.byte	$64
	.byte	$65
	.byte	$74
	.byte	$55
	.byte	$75
	.byte	$52
	.byte	$69
	.byte	$54
	.byte	$51
	.byte	$74
	.byte	$0F
	.byte	$04
	.byte	$04
	.byte	$0C
	.byte	$42
	.byte	$51
	.byte	$55
	.byte	$42
	.byte	$54
	.byte	$55
	.byte	$53
	.byte	$6B
	.byte	$6C
	.byte	$6D
	.byte	$53
	.byte	$51
	.byte	$02
	.byte	$3A
	.byte	$3B
	.byte	$00
	.byte	$0F
	.byte	$06
	.byte	$08
	.byte	$0C
	.byte	$51
	.byte	$40
	.byte	$41
	.byte	$56
	.byte	$55
	.byte	$57
	.byte	$56
	.byte	$56
	.byte	$00
	.byte	$3C
	.byte	$10
	.byte	$02
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$01
	.byte	$0E
	.byte	$07
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$08
	.byte	$09
	.byte	$0A
	.byte	$37
	.byte	$37
	.byte	$37
	.byte	$38
	.byte	$38
	.byte	$37
	.byte	$37
	.byte	$38
	.byte	$38
	.byte	$37
	.byte	$38
	.byte	$38
	.byte	$37
	.byte	$37
	.byte	$38
	.byte	$37
_metatile:
	.byte	$7B
	.byte	$7C
	.byte	$8B
	.byte	$8C
	.byte	$00
	.byte	$7D
	.byte	$7E
	.byte	$8D
	.byte	$8E
	.byte	$00
	.byte	$9B
	.byte	$9C
	.byte	$AB
	.byte	$AC
	.byte	$00
	.byte	$9D
	.byte	$9E
	.byte	$AD
	.byte	$AE
	.byte	$00
	.byte	$BE
	.byte	$AF
	.byte	$7B
	.byte	$7C
	.byte	$00
	.byte	$BE
	.byte	$BE
	.byte	$8B
	.byte	$8C
	.byte	$00
	.byte	$BE
	.byte	$BF
	.byte	$8D
	.byte	$8E
	.byte	$00
	.byte	$BE
	.byte	$BE
	.byte	$AD
	.byte	$AE
	.byte	$00
	.byte	$BE
	.byte	$B9
	.byte	$9B
	.byte	$9C
	.byte	$00
	.byte	$BE
	.byte	$BE
	.byte	$9D
	.byte	$9E
	.byte	$00
	.byte	$BE
	.byte	$BB
	.byte	$AB
	.byte	$AC
	.byte	$00
	.byte	$BE
	.byte	$AF
	.byte	$AD
	.byte	$AE
	.byte	$00
	.byte	$BE
	.byte	$BD
	.byte	$7B
	.byte	$7C
	.byte	$00
	.byte	$BE
	.byte	$BD
	.byte	$7D
	.byte	$7E
	.byte	$00
	.byte	$BA
	.byte	$BF
	.byte	$9B
	.byte	$9C
	.byte	$00
	.byte	$BA
	.byte	$B8
	.byte	$9D
	.byte	$9E
	.byte	$00
	.byte	$7B
	.byte	$AE
	.byte	$7C
	.byte	$7B
	.byte	$00
	.byte	$8B
	.byte	$8C
	.byte	$9B
	.byte	$9C
	.byte	$00
	.byte	$8D
	.byte	$8E
	.byte	$9D
	.byte	$9E
	.byte	$00
	.byte	$7B
	.byte	$7C
	.byte	$8B
	.byte	$01
	.byte	$00
	.byte	$AD
	.byte	$8E
	.byte	$AE
	.byte	$01
	.byte	$00
	.byte	$AD
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$7D
	.byte	$7E
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$9D
	.byte	$9E
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$AB
	.byte	$AC
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$7B
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$7B
	.byte	$AD
	.byte	$01
	.byte	$AE
	.byte	$00
	.byte	$7B
	.byte	$7C
	.byte	$01
	.byte	$7B
	.byte	$00
	.byte	$7A
	.byte	$7C
	.byte	$8B
	.byte	$8C
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$7A
	.byte	$00
	.byte	$7B
	.byte	$6A
	.byte	$7C
	.byte	$7B
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$6A
	.byte	$00
	.byte	$00
	.byte	$75
	.byte	$76
	.byte	$85
	.byte	$86
	.byte	$02
	.byte	$65
	.byte	$66
	.byte	$85
	.byte	$86
	.byte	$02
	.byte	$75
	.byte	$76
	.byte	$95
	.byte	$96
	.byte	$02
	.byte	$74
	.byte	$76
	.byte	$84
	.byte	$86
	.byte	$02
	.byte	$75
	.byte	$77
	.byte	$85
	.byte	$87
	.byte	$02
	.byte	$64
	.byte	$66
	.byte	$84
	.byte	$86
	.byte	$02
	.byte	$65
	.byte	$67
	.byte	$85
	.byte	$87
	.byte	$02
	.byte	$74
	.byte	$76
	.byte	$94
	.byte	$96
	.byte	$02
	.byte	$75
	.byte	$77
	.byte	$95
	.byte	$97
	.byte	$02
	.byte	$DF
	.byte	$DF
	.byte	$DC
	.byte	$CD
	.byte	$03
	.byte	$DF
	.byte	$CE
	.byte	$CE
	.byte	$DB
	.byte	$03
	.byte	$CD
	.byte	$CE
	.byte	$EE
	.byte	$EE
	.byte	$03
	.byte	$DF
	.byte	$CF
	.byte	$DC
	.byte	$CC
	.byte	$03
	.byte	$34
	.byte	$CF
	.byte	$DF
	.byte	$33
	.byte	$03
	.byte	$DF
	.byte	$CF
	.byte	$33
	.byte	$CF
	.byte	$03
	.byte	$CB
	.byte	$CE
	.byte	$EF
	.byte	$EE
	.byte	$03
	.byte	$65
	.byte	$66
	.byte	$95
	.byte	$96
	.byte	$02
	.byte	$64
	.byte	$66
	.byte	$94
	.byte	$96
	.byte	$02
	.byte	$65
	.byte	$67
	.byte	$95
	.byte	$97
	.byte	$02
	.byte	$EB
	.byte	$EB
	.byte	$FB
	.byte	$FC
	.byte	$03
	.byte	$EB
	.byte	$EA
	.byte	$FC
	.byte	$FB
	.byte	$03
	.byte	$FA
	.byte	$EB
	.byte	$FC
	.byte	$FC
	.byte	$03
	.byte	$EB
	.byte	$EC
	.byte	$FB
	.byte	$FC
	.byte	$03
	.byte	$98
	.byte	$99
	.byte	$A8
	.byte	$A9
	.byte	$03
	.byte	$9A
	.byte	$98
	.byte	$AA
	.byte	$A8
	.byte	$03
	.byte	$01
	.byte	$01
	.byte	$9A
	.byte	$98
	.byte	$03
	.byte	$7B
	.byte	$8B
	.byte	$AD
	.byte	$9B
	.byte	$00
	.byte	$8E
	.byte	$7B
	.byte	$9C
	.byte	$AE
	.byte	$00
	.byte	$8B
	.byte	$7C
	.byte	$9B
	.byte	$AD
	.byte	$00
	.byte	$0A
	.byte	$0B
	.byte	$0A
	.byte	$0B
	.byte	$02
	.byte	$0A
	.byte	$0B
	.byte	$0A
	.byte	$0B
	.byte	$02
	.byte	$CA
	.byte	$CA
	.byte	$DA
	.byte	$DA
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$63
	.byte	$73
	.byte	$03
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$63
	.byte	$03
	.byte	$01
	.byte	$01
	.byte	$73
	.byte	$01
	.byte	$03
	.byte	$12
	.byte	$13
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$12
	.byte	$13
	.byte	$00
	.byte	$EF
	.byte	$9F
	.byte	$01
	.byte	$01
	.byte	$03
	.byte	$EF
	.byte	$EF
	.byte	$EE
	.byte	$EF
	.byte	$03
	.byte	$ED
	.byte	$ED
	.byte	$36
	.byte	$37
	.byte	$03
	.byte	$ED
	.byte	$38
	.byte	$37
	.byte	$00
	.byte	$03
	.byte	$39
	.byte	$ED
	.byte	$00
	.byte	$39
	.byte	$03
	.byte	$02
	.byte	$0D
	.byte	$0E
	.byte	$02
	.byte	$03
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$1F
	.byte	$02
	.byte	$02
	.byte	$2F
	.byte	$03
	.byte	$1B
	.byte	$0C
	.byte	$02
	.byte	$01
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0F
	.byte	$3F
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$2A
	.byte	$01
	.byte	$03
	.byte	$1A
	.byte	$01
	.byte	$01
	.byte	$2A
	.byte	$03
	.byte	$1A
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$03
	.byte	$F2
	.byte	$F2
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$F3
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$D4
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$80
	.byte	$81
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$82
	.byte	$82
	.byte	$03
	.byte	$01
	.byte	$2A
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$1A
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$AA
	.byte	$03
	.byte	$E8
	.byte	$03
	.byte	$A8
	.byte	$A9
	.byte	$68
	.byte	$FC
	.byte	$03
	.byte	$8A
	.byte	$03
	.byte	$F8
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$E9
	.byte	$03
	.byte	$03
	.byte	$08
	.byte	$19
	.byte	$09
	.byte	$18
	.byte	$02
	.byte	$08
	.byte	$19
	.byte	$08
	.byte	$18
	.byte	$02
	.byte	$B1
	.byte	$B2
	.byte	$08
	.byte	$18
	.byte	$02
	.byte	$D4
	.byte	$B0
	.byte	$F3
	.byte	$C0
	.byte	$02
	.byte	$08
	.byte	$19
	.byte	$C1
	.byte	$C2
	.byte	$02
	.byte	$B3
	.byte	$F3
	.byte	$C3
	.byte	$D4
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$F0
	.byte	$02
	.byte	$F1
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$14
	.byte	$04
	.byte	$15
	.byte	$04
	.byte	$02
	.byte	$15
	.byte	$04
	.byte	$15
	.byte	$05
	.byte	$02
	.byte	$E5
	.byte	$E6
	.byte	$14
	.byte	$04
	.byte	$02
	.byte	$D4
	.byte	$E4
	.byte	$F3
	.byte	$F4
	.byte	$02
	.byte	$14
	.byte	$04
	.byte	$F5
	.byte	$F6
	.byte	$02
	.byte	$E7
	.byte	$F3
	.byte	$F7
	.byte	$D4
	.byte	$02
	.byte	$00
	.byte	$E2
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$E3
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$17
	.byte	$06
	.byte	$17
	.byte	$02
	.byte	$07
	.byte	$16
	.byte	$07
	.byte	$17
	.byte	$02
	.byte	$06
	.byte	$17
	.byte	$07
	.byte	$17
	.byte	$02
	.byte	$E0
	.byte	$E1
	.byte	$06
	.byte	$16
	.byte	$02
	.byte	$D4
	.byte	$D0
	.byte	$F2
	.byte	$F2
	.byte	$02
	.byte	$D1
	.byte	$F3
	.byte	$F2
	.byte	$F2
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$D2
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$D3
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$AA
	.byte	$AA
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$A9
	.byte	$A9
	.byte	$78
	.byte	$69
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$89
	.byte	$00
	.byte	$03
	.byte	$8A
	.byte	$00
	.byte	$8A
	.byte	$00
	.byte	$03
	.byte	$8A
	.byte	$00
	.byte	$79
	.byte	$00
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$F9
	.byte	$03
	.byte	$F9
	.byte	$E9
	.byte	$AA
	.byte	$AA
	.byte	$03
	.byte	$90
	.byte	$90
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$91
	.byte	$92
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$92
	.byte	$92
	.byte	$02
	.byte	$92
	.byte	$90
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$92
	.byte	$90
	.byte	$02
	.byte	$01
	.byte	$92
	.byte	$90
	.byte	$00
	.byte	$02
	.byte	$7A
	.byte	$32
	.byte	$32
	.byte	$DF
	.byte	$03
	.byte	$CF
	.byte	$89
	.byte	$DF
	.byte	$CF
	.byte	$03
	.byte	$DF
	.byte	$33
	.byte	$DE
	.byte	$DF
	.byte	$03
	.byte	$DD
	.byte	$CF
	.byte	$DF
	.byte	$34
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$7A
	.byte	$03
	.byte	$AA
	.byte	$A8
	.byte	$68
	.byte	$69
	.byte	$03
	.byte	$AA
	.byte	$A8
	.byte	$68
	.byte	$68
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$D7
	.byte	$A7
	.byte	$00
	.byte	$D7
	.byte	$A7
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$DF
	.byte	$CF
	.byte	$DC
	.byte	$DB
	.byte	$03
	.byte	$32
	.byte	$33
	.byte	$DE
	.byte	$DF
	.byte	$03
	.byte	$DF
	.byte	$35
	.byte	$CF
	.byte	$DD
	.byte	$03
	.byte	$32
	.byte	$34
	.byte	$32
	.byte	$33
	.byte	$03
	.byte	$33
	.byte	$35
	.byte	$34
	.byte	$35
	.byte	$03
	.byte	$00
	.byte	$7A
	.byte	$88
	.byte	$DF
	.byte	$03
	.byte	$00
	.byte	$88
	.byte	$88
	.byte	$CF
	.byte	$03
	.byte	$6A
	.byte	$00
	.byte	$CF
	.byte	$6A
	.byte	$03
	.byte	$89
	.byte	$00
	.byte	$A8
	.byte	$89
	.byte	$03
	.byte	$A9
	.byte	$6A
	.byte	$A9
	.byte	$AA
	.byte	$03
	.byte	$01
	.byte	$FF
	.byte	$FF
	.byte	$00
	.byte	$03
	.byte	$FF
	.byte	$01
	.byte	$00
	.byte	$FE
	.byte	$03
	.byte	$EF
	.byte	$EF
	.byte	$FE
	.byte	$FD
	.byte	$03
	.byte	$ED
	.byte	$EE
	.byte	$FE
	.byte	$FF
	.byte	$03
	.byte	$FD
	.byte	$FE
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$FF
	.byte	$FD
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$03
	.byte	$03
	.byte	$3F
	.byte	$03
	.byte	$05
	.byte	$03
	.byte	$03
	.byte	$05
	.byte	$03
	.byte	$2F
	.byte	$03
	.byte	$03
	.byte	$01
	.byte	$1F
	.byte	$1F
	.byte	$02
	.byte	$03
	.byte	$0F
	.byte	$02
	.byte	$01
	.byte	$0F
	.byte	$03
	.byte	$02
	.byte	$2F
	.byte	$11
	.byte	$11
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$11
	.byte	$11
	.byte	$03
	.byte	$03
	.byte	$61
	.byte	$60
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$62
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$61
	.byte	$03
	.byte	$03
	.byte	$60
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$72
	.byte	$03
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$71
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$70
	.byte	$03
	.byte	$C8
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$C8
	.byte	$C9
	.byte	$01
	.byte	$D9
	.byte	$01
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$3F
	.byte	$03
	.byte	$02
	.byte	$3F
	.byte	$03
	.byte	$01
	.byte	$01
	.byte	$0D
	.byte	$01
	.byte	$03
	.byte	$03
	.byte	$0E
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$A1
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$A2
	.byte	$03
	.byte	$03
	.byte	$A2
	.byte	$03
	.byte	$03
	.byte	$A1
	.byte	$03
	.byte	$A0
	.byte	$03
	.byte	$03
	.byte	$A1
	.byte	$03
	.byte	$83
	.byte	$03
	.byte	$03
	.byte	$83
	.byte	$03
	.byte	$83
	.byte	$93
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$83
	.byte	$03
	.byte	$03
	.byte	$93
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$83
	.byte	$03
	.byte	$03
	.byte	$83
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$C9
	.byte	$D9
	.byte	$D8
	.byte	$01
	.byte	$01
	.byte	$B5
	.byte	$B6
	.byte	$C5
	.byte	$C6
	.byte	$02
	.byte	$01
	.byte	$B4
	.byte	$01
	.byte	$C4
	.byte	$02
	.byte	$B7
	.byte	$01
	.byte	$C7
	.byte	$01
	.byte	$02
	.byte	$01
	.byte	$01
	.byte	$A5
	.byte	$A6
	.byte	$02
	.byte	$D5
	.byte	$D6
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$6B
	.byte	$6B
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$10
	.byte	$10
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$9F
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$C8
	.byte	$C9
	.byte	$D8
	.byte	$D9
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$D8
	.byte	$D9
	.byte	$01
	.byte	$C8
	.byte	$01
	.byte	$D8
	.byte	$D9
	.byte	$01
	.byte	$01
	.byte	$C9
	.byte	$D8
	.byte	$D9
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$D8
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$D9
	.byte	$01
	.byte	$01
	.byte	$D9
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$00
	.byte	$5E
	.byte	$6C
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$6B
	.byte	$6C
	.byte	$00
	.byte	$6B
	.byte	$5E
	.byte	$03
	.byte	$6D
	.byte	$00
	.byte	$6B
	.byte	$5E
	.byte	$6D
	.byte	$5D
	.byte	$00
	.byte	$6D
	.byte	$03
	.byte	$03
	.byte	$6D
	.byte	$00
	.byte	$6D
	.byte	$6D
	.byte	$03
	.byte	$03
	.byte	$00
	.byte	$6D
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$00
	.byte	$6D
	.byte	$40
	.byte	$6D
	.byte	$40
	.byte	$00
	.byte	$40
	.byte	$6E
	.byte	$6F
	.byte	$40
	.byte	$00
	.byte	$6D
	.byte	$14
	.byte	$03
	.byte	$6F
	.byte	$00
	.byte	$40
	.byte	$6E
	.byte	$40
	.byte	$40
	.byte	$00
	.byte	$6E
	.byte	$6E
	.byte	$40
	.byte	$6E
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$1E
	.byte	$1E
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$1C
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$1D
	.byte	$00
	.byte	$01
	.byte	$6D
	.byte	$6D
	.byte	$A3
	.byte	$A4
	.byte	$00
	.byte	$5D
	.byte	$5B
	.byte	$40
	.byte	$9F
	.byte	$00
	.byte	$5C
	.byte	$80
	.byte	$9F
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$5B
	.byte	$5C
	.byte	$00
	.byte	$5F
	.byte	$00
	.byte	$9F
	.byte	$5F
	.byte	$00
	.byte	$5B
	.byte	$5C
	.byte	$9F
	.byte	$01
	.byte	$00
	.byte	$6B
	.byte	$6C
	.byte	$01
	.byte	$A3
	.byte	$00
	.byte	$6D
	.byte	$03
	.byte	$A4
	.byte	$03
	.byte	$00
	.byte	$A3
	.byte	$A4
	.byte	$9F
	.byte	$9F
	.byte	$00
	.byte	$03
	.byte	$6D
	.byte	$A4
	.byte	$03
	.byte	$00
	.byte	$9F
	.byte	$9F
	.byte	$9F
	.byte	$9F
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$9F
	.byte	$9F
	.byte	$00
	.byte	$9F
	.byte	$01
	.byte	$9F
	.byte	$9F
	.byte	$00
	.byte	$6E
	.byte	$9F
	.byte	$6E
	.byte	$8F
	.byte	$00
	.byte	$8F
	.byte	$7F
	.byte	$6E
	.byte	$6E
	.byte	$00
	.byte	$9F
	.byte	$9F
	.byte	$8F
	.byte	$7F
	.byte	$00
	.byte	$7F
	.byte	$9F
	.byte	$6E
	.byte	$8F
	.byte	$00
.segment	"BANK3"
.segment	"BANK4"
.segment	"BANK5"
.segment	"BANK6"
.segment	"CODE"
_palette_bg:
	.byte	$21
	.byte	$0F
	.byte	$00
	.byte	$10
	.byte	$21
	.byte	$0F
	.byte	$30
	.byte	$08
	.byte	$21
	.byte	$0F
	.byte	$17
	.byte	$06
	.byte	$21
	.byte	$0F
	.byte	$19
	.byte	$29
_palette_sp:
	.byte	$21
	.byte	$17
	.byte	$24
	.byte	$36
	.byte	$21
	.byte	$05
	.byte	$16
	.byte	$37
	.byte	$21
	.byte	$0F
	.byte	$11
	.byte	$30
	.byte	$21
	.byte	$17
	.byte	$3D
	.byte	$37

.segment	"BSS"

_bankLevel:
	.res	1,$00
_bankBuffer:
	.res	10,$00
.segment	"ZEROPAGE"
_direction:
	.res	1,$00
_direction_y:
	.res	1,$00
_arg1:
	.res	1,$00
_arg2:
	.res	1,$00
_pad1:
	.res	1,$00
_pad1_new:
	.res	1,$00
_char_state:
	.res	1,$00
_song:
	.res	1,$00
_sound:
	.res	1,$00
_temp_x:
	.res	2,$00
_temp_y:
	.res	2,$00
_temp_sprite:
	.res	2,$00
_old_x:
	.res	1,$00
_old_y:
	.res	1,$00
_eject_L:
	.res	1,$00
_eject_R:
	.res	1,$00
_eject_D:
	.res	1,$00
_eject_U:
	.res	1,$00
_collision_L:
	.res	1,$00
_collision_R:
	.res	1,$00
_collision_U:
	.res	1,$00
_collision_D:
	.res	1,$00
_coordinates:
	.res	1,$00
_location_with_scroll:
	.res	2,$00
_collision:
	.res	1,$00
_nametable_to_load:
	.res	1,$00
_level:
	.res	1,$00
_offset:
	.res	1,$00
_address:
	.res	2,$00
_x:
	.res	1,$00
_y:
	.res	1,$00
_nt:
	.res	1,$00
_index:
	.res	1,$00
_map:
	.res	1,$00
_scroll_x:
	.res	2,$00
_scroll_y:
	.res	2,$00
_max_rooms:
	.res	1,$00
_max_scroll:
	.res	2,$00
_temp_room:
	.res	1,$00
.segment	"BSS"
_c_map:
	.res	240,$00
_c_map2:
	.res	240,$00
_Generic:
	.res	4,$00
_Generic2:
	.res	4,$00
.segment	"XRAM"
_wram_array:
	.res	8192,$00

; ---------------------------------------------------------------
; void __near__ banked_call (unsigned char, __near__ __near__ function returning void *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_banked_call: near

.segment	"CODE"

;
; void banked_call(unsigned char bankId, void (*method)(void)) {
;
	jsr     pushax
;
; bank_push(bankId);
;
	ldy     #$02
	lda     (sp),y
	jsr     _bank_push
;
; (*method)();
;
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     callax
;
; bank_pop();
;
	jsr     _bank_pop
;
; }
;
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ bank_push (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_bank_push: near

.segment	"CODE"

;
; void bank_push(unsigned char bankId) {
;
	jsr     pusha
;
; bankBuffer[bankLevel] = get_prg_bank();
;
	lda     #<(_bankBuffer)
	ldx     #>(_bankBuffer)
	clc
	adc     _bankLevel
	bcc     L000B
	inx
L000B:	jsr     pushax
	jsr     _get_prg_bank
	ldy     #$00
	jsr     staspidx
;
; ++bankLevel;
;
	inc     _bankLevel
;
; set_prg_bank(bankId);
;
	ldy     #$00
	lda     (sp),y
	jsr     _set_prg_bank
;
; }
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ bank_pop (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_bank_pop: near

.segment	"CODE"

;
; if (bankLevel != 0) {
;
	lda     _bankLevel
	beq     L0011
;
; --bankLevel;
;
	dec     _bankLevel
;
; set_prg_bank(bankBuffer[bankLevel]);
;
	ldy     _bankLevel
	lda     _bankBuffer,y
	jmp     _set_prg_bank
;
; }
;
L0011:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_collision_sub (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_collision_sub: near

.segment	"BANK0"

;
; if (temp_y >= 0xf0)
;
	lda     _temp_y
	cmp     #$F0
	lda     _temp_y+1
	sbc     #$00
	bcc     L0137
;
; return 0;
;
	ldx     #$00
	txa
	rts
;
; coordinates = (temp_x >> 4) + (temp_y & 0xf0);
;
L0137:	lda     _temp_x
	ldx     _temp_x+1
	jsr     shrax4
	sta     ptr1
	lda     _temp_y
	and     #$F0
	clc
	adc     ptr1
	sta     _coordinates
;
; map = temp_room & 1; // high byte
;
	lda     _temp_room
	and     #$01
	sta     _map
;
; if (!map)
;
	lda     _map
	bne     L0140
;
; collision = c_map[coordinates];
;
	ldy     _coordinates
	lda     _c_map,y
;
; else
;
	jmp     L091B
;
; collision = c_map2[coordinates];
;
L0140:	ldy     _coordinates
	lda     _c_map2,y
L091B:	sta     _collision
;
; return metatile_colision_map[collision];
;
	ldy     _collision
	ldx     #$00
	lda     _metatile_colision_map,y
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ bg_collision_fast (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_collision_fast: near

.segment	"BANK0"

;
; collision_L = 0;
;
	lda     #$00
	sta     _collision_L
;
; collision_R = 0;
;
	sta     _collision_R
;
; collision_D = 0;
;
	sta     _collision_D
;
; if (Generic.y >= 0xf0)
;
	lda     _Generic+1
	cmp     #$F0
;
; return;
;
	bcc     L091F
;
; }
;
	rts
;
; location_with_scroll = Generic.x + scroll_x;
;
L091F:	lda     _Generic
	clc
	adc     _scroll_x
	pha
	lda     #$00
	adc     _scroll_x+1
	sta     _location_with_scroll+1
	pla
	sta     _location_with_scroll
;
; temp_x = location_with_scroll & 0xff;  // low byte x
;
	ldx     #$00
	sta     _temp_x
	stx     _temp_x+1
;
; temp_room = location_with_scroll >> 8; // high byte x
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; temp_y = Generic.y + 6; // y middle
;
	lda     _Generic+1
	clc
	adc     #$06
	bcc     L015F
	inx
L015F:	sta     _temp_y
	stx     _temp_y+1
;
; bg_collision_sub();
;
	jsr     _bg_collision_sub
;
; if (bg_collision_sub() & COL_ALL)
;
	jsr     _bg_collision_sub
	and     #$40
	beq     L091D
;
; ++collision_L;
;
	inc     _collision_L
;
; location_with_scroll += Generic.width;
;
L091D:	lda     _Generic+2
	clc
	adc     _location_with_scroll
	sta     _location_with_scroll
	lda     #$00
	adc     _location_with_scroll+1
	sta     _location_with_scroll+1
;
; temp_x = location_with_scroll & 0xff;  // low byte x
;
	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_room = location_with_scroll >> 8; // high byte x
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; bg_collision_sub();
;
	jsr     _bg_collision_sub
;
; if (bg_collision_sub() & COL_ALL)
;
	jsr     _bg_collision_sub
	and     #$40
	beq     L091E
;
; ++collision_R;
;
	inc     _collision_R
;
; location_with_scroll -= (Generic.width >> 1); // middle of character
;
L091E:	lda     _Generic+2
	lsr     a
	eor     #$FF
	sec
	adc     _location_with_scroll
	sta     _location_with_scroll
	lda     #$FF
	adc     _location_with_scroll+1
	sta     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll;          // low byte
;
	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_y += 6;
;
	lda     #$06
	clc
	adc     _temp_y
	sta     _temp_y
	bcc     L0175
	inc     _temp_y+1
;
; if (bg_collision_sub() & COL_ALL)
;
L0175:	jsr     _bg_collision_sub
	and     #$40
	beq     L0176
;
; ++collision_D;
;
	inc     _collision_D
;
; }
;
L0176:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_coll_L (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_coll_L: near

.segment	"BANK0"

;
; location_with_scroll = Generic.x + scroll_x;
;
	lda     _Generic
	clc
	adc     _scroll_x
	sta     _location_with_scroll
	lda     #$00
	adc     _scroll_x+1
	sta     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll;   // low byte
;
	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_room = location_with_scroll >> 8; // high byte
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; eject_L = temp_x | 0xf0;
;
	lda     _temp_x
	ora     #$F0
	sta     _eject_L
;
; temp_y = Generic.y + 2;
;
	ldx     #$00
	lda     _Generic+1
	clc
	adc     #$02
	bcc     L0184
	inx
L0184:	sta     _temp_y
	stx     _temp_y+1
;
; if (bg_collision_sub() & COL_ALL)
;
	jsr     _bg_collision_sub
	ldx     #$00
	and     #$40
	beq     L0921
;
; return 1;
;
	lda     #$01
	rts
;
; temp_y = Generic.y + Generic.height;
;
L0921:	lda     _Generic+1
	clc
	adc     _Generic+3
	bcc     L0920
	inx
L0920:	sta     _temp_y
	stx     _temp_y+1
;
; temp_y -= 2;
;
	lda     _temp_y
	sec
	sbc     #$02
	sta     _temp_y
	bcs     L018C
	dec     _temp_y+1
;
; if (bg_collision_sub() & COL_ALL)
;
L018C:	jsr     _bg_collision_sub
	ldx     #$00
	and     #$40
	beq     L0923
;
; return 1;
;
	lda     #$01
	rts
;
; }
;
L0923:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_coll_R (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_coll_R: near

.segment	"BANK0"

;
; location_with_scroll = Generic.x + scroll_x + Generic.width;
;
	lda     _Generic
	clc
	adc     _scroll_x
	pha
	lda     #$00
	adc     _scroll_x+1
	tax
	pla
	clc
	adc     _Generic+2
	bcc     L0924
	inx
L0924:	sta     _location_with_scroll
	stx     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll;   // low byte
;
	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_room = location_with_scroll >> 8; // high byte
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; eject_R = (temp_x + 1) & 0x0f;
;
	lda     _temp_x
	clc
	adc     #$01
	and     #$0F
	sta     _eject_R
;
; temp_y = Generic.y + 2;
;
	ldx     #$00
	lda     _Generic+1
	clc
	adc     #$02
	bcc     L019E
	inx
L019E:	sta     _temp_y
	stx     _temp_y+1
;
; if (bg_collision_sub() & COL_ALL)
;
	jsr     _bg_collision_sub
	ldx     #$00
	and     #$40
	beq     L0926
;
; return 1;
;
	lda     #$01
	rts
;
; temp_y = Generic.y + Generic.height;
;
L0926:	lda     _Generic+1
	clc
	adc     _Generic+3
	bcc     L0925
	inx
L0925:	sta     _temp_y
	stx     _temp_y+1
;
; temp_y -= 2;
;
	lda     _temp_y
	sec
	sbc     #$02
	sta     _temp_y
	bcs     L01A6
	dec     _temp_y+1
;
; if (bg_collision_sub() & COL_ALL)
;
L01A6:	jsr     _bg_collision_sub
	ldx     #$00
	and     #$40
	beq     L0928
;
; return 1;
;
	lda     #$01
	rts
;
; }
;
L0928:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_coll_ladder (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_coll_ladder: near

.segment	"BANK0"

;
; location_with_scroll = Generic.x + scroll_x + 7;
;
	lda     _Generic
	clc
	adc     _scroll_x
	pha
	lda     #$00
	adc     _scroll_x+1
	tax
	pla
	clc
	adc     #$07
	bcc     L01AE
	inx
L01AE:	sta     _location_with_scroll
	stx     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll; // low byte
;
	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_y = Generic.y + Generic.height;
;
	ldx     #$00
	lda     _Generic+1
	clc
	adc     _Generic+3
	bcc     L0929
	inx
L0929:	sta     _temp_y
	stx     _temp_y+1
;
; temp_y -= 2;
;
	lda     _temp_y
	sec
	sbc     #$02
	sta     _temp_y
	bcs     L01B5
	dec     _temp_y+1
;
; if (bg_collision_sub() & COL_LADDER || bg_collision_sub() & COL_LADDER_TOP)
;
L01B5:	jsr     _bg_collision_sub
	and     #$01
	bne     L092A
	jsr     _bg_collision_sub
	and     #$02
	bne     L092A
	tax
	rts
;
; return location_with_scroll;
;
L092A:	ldx     #$00
	lda     _location_with_scroll
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_coll_ladder_top_at_player (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_coll_ladder_top_at_player: near

.segment	"BANK0"

;
; location_with_scroll = Generic.x + scroll_x + 7;
;
	lda     _Generic
	clc
	adc     _scroll_x
	pha
	lda     #$00
	adc     _scroll_x+1
	tax
	pla
	clc
	adc     #$07
	bcc     L01BE
	inx
L01BE:	sta     _location_with_scroll
	stx     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll; // low byte
;
	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_y = Generic.y + Generic.height;
;
	ldx     #$00
	lda     _Generic+1
	clc
	adc     _Generic+3
	bcc     L092D
	inx
L092D:	sta     _temp_y
	stx     _temp_y+1
;
; temp_y -= 2;
;
	lda     _temp_y
	sec
	sbc     #$02
	sta     _temp_y
	bcs     L01C5
	dec     _temp_y+1
;
; if (bg_collision_sub() & COL_LADDER)
;
L01C5:	jsr     _bg_collision_sub
	ldx     #$00
	and     #$01
	beq     L092F
;
; return 1;
;
	lda     #$01
	rts
;
; }
;
L092F:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_coll_ladder_top_under_player (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_coll_ladder_top_under_player: near

.segment	"BANK0"

;
; location_with_scroll = Generic.x + scroll_x + 7;
;
	lda     _Generic
	clc
	adc     _scroll_x
	pha
	lda     #$00
	adc     _scroll_x+1
	tax
	pla
	clc
	adc     #$07
	bcc     L01CD
	inx
L01CD:	sta     _location_with_scroll
	stx     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll; // low byte
;
	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_y = Generic.y + Generic.height;
;
	ldx     #$00
	lda     _Generic+1
	clc
	adc     _Generic+3
	bcc     L0930
	inx
L0930:	sta     _temp_y
	stx     _temp_y+1
;
; temp_y += 4;
;
	lda     #$04
	clc
	adc     _temp_y
	sta     _temp_y
	bcc     L01D4
	inc     _temp_y+1
;
; if (bg_collision_sub() & COL_LADDER_TOP)
;
L01D4:	jsr     _bg_collision_sub
	ldx     #$00
	and     #$02
	beq     L0932
;
; return 1;
;
	lda     #$01
	rts
;
; }
;
L0932:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_coll_U (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_coll_U: near

.segment	"BANK0"

;
; location_with_scroll = Generic.x + scroll_x;
;
	lda     _Generic
	clc
	adc     _scroll_x
	sta     _location_with_scroll
	lda     #$00
	adc     _scroll_x+1
	sta     _location_with_scroll+1
;
; location_with_scroll += 2;
;
	lda     #$02
	clc
	adc     _location_with_scroll
	sta     _location_with_scroll
	bcc     L01DE
	inc     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll;   // low byte
;
L01DE:	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_room = location_with_scroll >> 8; // high byte
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; temp_y = Generic.y;
;
	lda     #$00
	sta     _temp_y+1
	lda     _Generic+1
	sta     _temp_y
;
; eject_U = temp_y | 0xf0;
;
	ora     #$F0
	sta     _eject_U
;
; if (bg_collision_sub() & COL_ALL)
;
	jsr     _bg_collision_sub
	and     #$40
	beq     L0934
;
; return 1;
;
	ldx     #$00
	lda     #$01
	rts
;
; location_with_scroll = Generic.x + scroll_x + Generic.width;
;
L0934:	lda     _Generic
	clc
	adc     _scroll_x
	pha
	lda     #$00
	adc     _scroll_x+1
	tax
	pla
	clc
	adc     _Generic+2
	bcc     L0933
	inx
L0933:	sta     _location_with_scroll
	stx     _location_with_scroll+1
;
; location_with_scroll -= 2;
;
	lda     _location_with_scroll
	sec
	sbc     #$02
	sta     _location_with_scroll
	bcs     L01EE
	dec     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll;   // low byte
;
L01EE:	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_room = location_with_scroll >> 8; // high byte
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; if (bg_collision_sub() & COL_ALL)
;
	jsr     _bg_collision_sub
	ldx     #$00
	and     #$40
	beq     L0936
;
; return 1;
;
	lda     #$01
	rts
;
; }
;
L0936:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_coll_D (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_coll_D: near

.segment	"BANK0"

;
; location_with_scroll = Generic.x + scroll_x;
;
	lda     _Generic
	clc
	adc     _scroll_x
	sta     _location_with_scroll
	lda     #$00
	adc     _scroll_x+1
	sta     _location_with_scroll+1
;
; location_with_scroll += 2;
;
	lda     #$02
	clc
	adc     _location_with_scroll
	sta     _location_with_scroll
	bcc     L01FC
	inc     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll;   // low byte
;
L01FC:	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_room = location_with_scroll >> 8; // high byte
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; temp_y = Generic.y + Generic.height;
;
	ldx     #$00
	lda     _Generic+1
	clc
	adc     _Generic+3
	bcc     L0937
	inx
L0937:	sta     _temp_y
	stx     _temp_y+1
;
; if ((temp_y & 0x0f) > 3)
;
	and     #$0F
	cmp     #$04
	lda     #$00
	bcc     L0203
;
; return 0; // bug fix
;
	tax
	rts
;
; eject_D = (temp_y + 1) & 0x0f;
;
L0203:	lda     _temp_y
	clc
	adc     #$01
	and     #$0F
	sta     _eject_D
;
; if (bg_collision_sub() & COL_ALL || ((bg_collision_sub() & COL_LADDER_TOP)))
;
	jsr     _bg_collision_sub
	and     #$40
	bne     L093A
	jsr     _bg_collision_sub
	and     #$02
	beq     L093B
;
; return 1;
;
L093A:	ldx     #$00
	lda     #$01
	rts
;
; location_with_scroll = Generic.x + scroll_x + Generic.width;
;
L093B:	lda     _Generic
	clc
	adc     _scroll_x
	pha
	lda     #$00
	adc     _scroll_x+1
	tax
	pla
	clc
	adc     _Generic+2
	bcc     L0938
	inx
L0938:	sta     _location_with_scroll
	stx     _location_with_scroll+1
;
; location_with_scroll -= 2;
;
	lda     _location_with_scroll
	sec
	sbc     #$02
	sta     _location_with_scroll
	bcs     L0215
	dec     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll;   // low byte
;
L0215:	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_room = location_with_scroll >> 8; // high byte
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; if (bg_collision_sub() & COL_ALL || ((bg_collision_sub() & COL_LADDER_TOP)))
;
	jsr     _bg_collision_sub
	and     #$40
	bne     L093C
	jsr     _bg_collision_sub
	and     #$02
	bne     L093C
	tax
	rts
;
; return 1;
;
L093C:	ldx     #$00
	lda     #$01
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ bg_coll_D2 (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bg_coll_D2: near

.segment	"BANK0"

;
; location_with_scroll = Generic.x + scroll_x;
;
	lda     _Generic
	clc
	adc     _scroll_x
	sta     _location_with_scroll
	lda     #$00
	adc     _scroll_x+1
	sta     _location_with_scroll+1
;
; location_with_scroll += 2;
;
	lda     #$02
	clc
	adc     _location_with_scroll
	sta     _location_with_scroll
	bcc     L0226
	inc     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll;   // low byte
;
L0226:	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_room = location_with_scroll >> 8; // high byte
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; temp_y = Generic.y + Generic.height;
;
	ldx     #$00
	lda     _Generic+1
	clc
	adc     _Generic+3
	bcc     L093E
	inx
L093E:	sta     _temp_y
	stx     _temp_y+1
;
; temp_y += 2;
;
	lda     #$02
	clc
	adc     _temp_y
	sta     _temp_y
	bcc     L022F
	inc     _temp_y+1
;
; if (bg_collision_sub())
;
L022F:	jsr     _bg_collision_sub
	tax
	beq     L0940
;
; return 1;
;
	ldx     #$00
	lda     #$01
	rts
;
; location_with_scroll = Generic.x + scroll_x + Generic.width;
;
L0940:	lda     _Generic
	clc
	adc     _scroll_x
	pha
	txa
	adc     _scroll_x+1
	tax
	pla
	clc
	adc     _Generic+2
	bcc     L093F
	inx
L093F:	sta     _location_with_scroll
	stx     _location_with_scroll+1
;
; location_with_scroll -= 2;
;
	lda     _location_with_scroll
	sec
	sbc     #$02
	sta     _location_with_scroll
	bcs     L0237
	dec     _location_with_scroll+1
;
; temp_x = (char)location_with_scroll;   // low byte
;
L0237:	lda     #$00
	sta     _temp_x+1
	lda     _location_with_scroll
	sta     _temp_x
;
; temp_room = location_with_scroll >> 8; // high byte
;
	lda     _location_with_scroll+1
	sta     _temp_room
;
; if (bg_collision_sub())
;
	jsr     _bg_collision_sub
	tax
	beq     L0942
;
; return 1;
;
	ldx     #$00
	lda     #$01
	rts
;
; }
;
L0942:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ move_player (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_move_player: near

.segment	"BANK0"

;
; old_x = Player1.x; 
;
	lda     _Player1
	sta     _old_x
;
; if (pad1 & PAD_LEFT )
;
	lda     _pad1
	and     #$02
	beq     L0944
;
; direction = LEFT;
;
	lda     #$00
	sta     _direction
;
; if (Player1.vel_x >= DECEL)
;
	lda     _Player1+4
	cmp     #$32
	lda     _Player1+4+1
	sbc     #$00
	bvs     L0249
	eor     #$80
L0249:	bpl     L0247
;
; Player1.vel_x -= DECEL;
;
	lda     _Player1+4
	sec
	sbc     #$32
	sta     _Player1+4
	jcs     L0283
	dec     _Player1+4+1
;
; else if (Player1.vel_x > 0)
;
	jmp     L0283
L0247:	lda     _Player1+4
	cmp     #$01
	lda     _Player1+4+1
	sbc     #$00
	bvs     L0250
	eor     #$80
L0250:	bpl     L024E
;
; Player1.vel_x = 0;
;
	ldx     #$00
	txa
;
; else
;
	jmp     L0946
;
; Player1.vel_x -= ACCEL;
;
L024E:	lda     _Player1+4
	sec
	sbc     #$1E
	sta     _Player1+4
	bcs     L0256
	dec     _Player1+4+1
;
; if (Player1.vel_x < -MAX_SPEED)
;
L0256:	lda     _Player1+4
	cmp     #$A0
	lda     _Player1+4+1
	sbc     #$FE
	bvc     L0259
	eor     #$80
L0259:	jpl     L0283
;
; Player1.vel_x = -MAX_SPEED;
;
	ldx     #$FE
	lda     #$A0
;
; else if (pad1 & PAD_RIGHT)
;
	jmp     L0946
L0944:	lda     _pad1
	and     #$01
	beq     L025D
;
; direction = RIGHT;
;
	lda     #$01
	sta     _direction
;
; if (Player1.vel_x <= DECEL)
;
	lda     _Player1+4
	cmp     #$33
	lda     _Player1+4+1
	sbc     #$00
	bvc     L0263
	eor     #$80
L0263:	bpl     L0261
;
; Player1.vel_x += DECEL;
;
	lda     #$32
	clc
	adc     _Player1+4
	sta     _Player1+4
	jcc     L0283
	inc     _Player1+4+1
;
; else if (Player1.vel_x < 0)
;
	jmp     L0283
L0261:	ldx     _Player1+4+1
	cpx     #$80
	bcc     L0268
;
; Player1.vel_x = 0;
;
	ldx     #$00
	txa
;
; else
;
	jmp     L0946
;
; Player1.vel_x += ACCEL;
;
L0268:	lda     #$1E
	clc
	adc     _Player1+4
	sta     _Player1+4
	bcc     L026F
	inc     _Player1+4+1
;
; if (Player1.vel_x >= MAX_SPEED)
;
L026F:	lda     _Player1+4
	cmp     #$60
	lda     _Player1+4+1
	sbc     #$01
	bvs     L0272
	eor     #$80
L0272:	bpl     L0283
;
; Player1.vel_x = MAX_SPEED;
;
	ldx     #$01
	lda     #$60
;
; else
;
	jmp     L0946
;
; if (Player1.vel_x >= ACCEL)
;
L025D:	lda     _Player1+4
	cmp     #$1E
	lda     _Player1+4+1
	sbc     #$00
	bvs     L0278
	eor     #$80
L0278:	bpl     L0276
;
; Player1.vel_x -= ACCEL;
;
	lda     _Player1+4
	sec
	sbc     #$1E
	sta     _Player1+4
	bcs     L0283
	dec     _Player1+4+1
;
; else if (Player1.vel_x < -ACCEL)
;
	jmp     L0283
L0276:	lda     _Player1+4
	cmp     #$E2
	lda     _Player1+4+1
	sbc     #$FF
	bvc     L027F
	eor     #$80
L027F:	asl     a
	lda     #$00
	tax
	bcc     L0946
;
; Player1.vel_x += ACCEL;
;
	lda     #$1E
	clc
	adc     _Player1+4
	sta     _Player1+4
	bcc     L0283
	inc     _Player1+4+1
;
; else
;
	jmp     L0283
;
; Player1.vel_x = 0;
;
L0946:	sta     _Player1+4
	stx     _Player1+4+1
;
; Player1.x += Player1.vel_x;
;
L0283:	lda     _Player1+4
	clc
	adc     _Player1
	sta     _Player1
	lda     _Player1+4+1
	adc     _Player1+1
	sta     _Player1+1
;
; if (Player1.vel_y < 0x300)
;
	lda     _Player1+6
	cmp     #$00
	lda     _Player1+6+1
	sbc     #$03
	bvc     L028A
	eor     #$80
L028A:	bpl     L0288
;
; Player1.vel_y += GRAVITY;
;
	lda     #$3C
	clc
	adc     _Player1+6
	sta     _Player1+6
	bcc     L028E
	inc     _Player1+6+1
;
; else
;
	jmp     L028E
;
; Player1.vel_y = 0x300; // consistent gravity
;
L0288:	ldx     #$03
	lda     #$00
	sta     _Player1+6
	stx     _Player1+6+1
;
; if (pad1 & PAD_A)
;
L028E:	lda     _pad1
	and     #$80
	beq     L0291
;
; Player1.vel_y = JUMP_VEL; // JUMP
;
	ldx     #$FD
	lda     #$F0
	sta     _Player1+6
	stx     _Player1+6+1
;
; Player1.y += Player1.vel_y; // add gravity to y; (make him go up or down)
;
L0291:	lda     _Player1+6
	clc
	adc     _Player1+2
	sta     _Player1+2
	lda     _Player1+6+1
	adc     _Player1+2+1
	sta     _Player1+2+1
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ check_player_colision (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_check_player_colision: near

.segment	"BANK0"

;
; Generic.x = high_byte(Player1.x); // this is much faster than passing a pointer
;
	lda     _Player1+1
	sta     _Generic
;
; Generic.y = high_byte(Player1.y);
;
	lda     _Player1+3
	sta     _Generic+1
;
; Generic.width = HERO_WIDTH;
;
	lda     #$0C
	sta     _Generic+2
;
; Generic.height = HERO_HEIGHT; 
;
	lda     #$14
	sta     _Generic+3
;
; if (Player1.vel_x < 0)
;
	ldx     _Player1+4+1
	cpx     #$80
	bcc     L02A2
;
; if (bg_coll_L())
;
	jsr     _bg_coll_L
	tax
	beq     L02BC
;
; high_byte(Player1.x) = high_byte(Player1.x) - eject_L;
;
	lda     _Player1+1
	sec
	sbc     _eject_L
	sta     _Player1+1
;
; Player1.vel_x = 0;
;
	lda     #$00
	sta     _Player1+4
	sta     _Player1+4+1
;
; if (Player1.x > 0xf000)
;
	lda     _Player1
	cmp     #$01
	lda     _Player1+1
	sbc     #$F0
	bcc     L02BC
;
; Player1.x = 0xf000;
;
	ldx     #$F0
;
; else if (Player1.vel_x > 0)
;
	jmp     L094B
L02A2:	lda     _Player1+4
	cmp     #$01
	lda     _Player1+4+1
	sbc     #$00
	bvs     L02B3
	eor     #$80
L02B3:	bpl     L02BC
;
; if (bg_coll_R())
;
	jsr     _bg_coll_R
	tax
	beq     L02BC
;
; high_byte(Player1.x) = high_byte(Player1.x) - eject_R;
;
	lda     _Player1+1
	sec
	sbc     _eject_R
	sta     _Player1+1
;
; Player1.vel_x = 0;
;
	lda     #$00
	sta     _Player1+4
	sta     _Player1+4+1
;
; if (Player1.x > 0xf000)
;
	lda     _Player1
	cmp     #$01
	lda     _Player1+1
	sbc     #$F0
	bcc     L02BC
;
; Player1.x = 0x0000;
;
	ldx     #$00
L094B:	lda     #$00
	sta     _Player1
	stx     _Player1+1
;
; if (Player1.y > 0xf000)   // limit how high he can go
;
L02BC:	lda     _Player1+2
	cmp     #$01
	lda     _Player1+2+1
	sbc     #$F0
	bcc     L02C0
;
; Player1.y = 0x0000;
;
	lda     #$00
	sta     _Player1+2
	sta     _Player1+2+1
;
; if (Player1.vel_y > 0) // he's going down
;
L02C0:	lda     _Player1+6
	cmp     #$01
	lda     _Player1+6+1
	sbc     #$00
	bvs     L02C6
	eor     #$80
L02C6:	bpl     L02C4
;
; if (bg_coll_D()) // if he's collising below
;
	jsr     _bg_coll_D
	tax
	beq     L02D7
;
; high_byte(Player1.y) = high_byte(Player1.y) - eject_D;
;
	lda     _Player1+3
	sec
	sbc     _eject_D
	sta     _Player1+3
;
; Player1.y &= 0xff00;
;
	ldx     _Player1+2+1
	lda     #$00
	sta     _Player1+2
	stx     _Player1+2+1
;
; if (Player1.vel_y > 0)
;
	lda     _Player1+6
	cmp     #$01
	lda     _Player1+6+1
	sbc     #$00
	bvs     L02D1
	eor     #$80
L02D1:	bpl     L02D7
;
; else if (Player1.vel_y < 0) // he's going up
;
	jmp     L094C
L02C4:	ldx     _Player1+6+1
	cpx     #$80
	bcc     L02D7
;
; if (bg_coll_U())
;
	jsr     _bg_coll_U
	tax
	beq     L02D7
;
; high_byte(Player1.y) = high_byte(Player1.y) - eject_U;
;
	lda     _Player1+3
	sec
	sbc     _eject_U
	sta     _Player1+3
;
; Player1.vel_y = 0;
;
L094C:	lda     #$00
	sta     _Player1+6
	sta     _Player1+6+1
;
; }
;
L02D7:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ bank0_player_movement (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bank0_player_movement: near

.segment	"BANK0"

;
; move_player();
;
	jsr     _move_player
;
; check_player_colision();
;
	jmp     _check_player_colision

.endproc

; ---------------------------------------------------------------
; void __near__ bank0_draw_player_sprite (void)
; ---------------------------------------------------------------

.segment	"BANK0"

.proc	_bank0_draw_player_sprite: near

.segment	"BANK0"

;
; temp_x = Player1.x >> 8;
;
	ldx     #$00
	lda     _Player1+1
	sta     _temp_x
	stx     _temp_x+1
;
; temp_y = Player1.y >> 8; 
;
	lda     _Player1+3
	sta     _temp_y
	stx     _temp_y+1
;
; temp_sprite = noah_box;  
;
	lda     #>(_noah_box)
	sta     _temp_sprite+1
	lda     #<(_noah_box)
	sta     _temp_sprite
;
; oam_meta_spr(temp_x, temp_y, temp_sprite);
;
	jsr     decsp2
	lda     _temp_x
	ldy     #$01
	sta     (sp),y
	lda     _temp_y
	dey
	sta     (sp),y
	lda     _temp_sprite
	ldx     _temp_sprite+1
	jmp     _oam_meta_spr

.endproc

; ---------------------------------------------------------------
; void __near__ function_bank1 (void)
; ---------------------------------------------------------------

.segment	"BANK1"

.proc	_function_bank1: near

.segment	"BANK1"

;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ function_bank2 (void)
; ---------------------------------------------------------------

.segment	"BANK2"

.proc	_function_bank2: near

.segment	"BANK2"

;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ bank2_load_room (void)
; ---------------------------------------------------------------

.segment	"BANK2"

.proc	_bank2_load_room: near

.segment	"BANK2"

;
; clear_vram_buffer();
;
	jsr     _clear_vram_buffer
;
; set_data_pointer(level0_0);
;
	lda     #<(_level0_0)
	ldx     #>(_level0_0)
	jsr     _set_data_pointer
;
; set_mt_pointer(metatile);
;
	lda     #<(_metatile)
	ldx     #>(_metatile)
	jsr     _set_mt_pointer
;
; for (y = 0;; y += 0x20)
;
	lda     #$00
L094F:	sta     _y
;
; for (x = 0;; x += 0x20)
;
	lda     #$00
L094E:	sta     _x
;
; address = get_ppu_addr(0, x, y);
;
	jsr     decsp2
	lda     #$00
	ldy     #$01
	sta     (sp),y
	lda     _x
	dey
	sta     (sp),y
	lda     _y
	jsr     _get_ppu_addr
	sta     _address
	stx     _address+1
;
; index = (y & 0xf0) + (x >> 4);
;
	lda     _y
	and     #$F0
	sta     ptr1
	lda     _x
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	clc
	adc     ptr1
	sta     _index
;
; buffer_4_mt(address, index); // ppu_address, index to the data
;
	lda     _address
	ldx     _address+1
	jsr     pushax
	lda     _index
	jsr     _buffer_4_mt
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; if (x == 0xe0)
;
	lda     _x
	cmp     #$E0
;
; break;
;
	beq     L0950
;
; for (x = 0;; x += 0x20)
;
	lda     #$20
	clc
	adc     _x
	jmp     L094E
;
; if (y == 0xe0)
;
L0950:	lda     _y
	cmp     #$E0
;
; break;
;
	beq     L089A
;
; for (y = 0;; y += 0x20)
;
	lda     #$20
	clc
	adc     _y
	jmp     L094F
;
; if (!map)
;
L089A:	lda     _map
	bne     L08BA
;
; memcpy(c_map, level0_0, 240); 
;
	tay
L08C0:	lda     _level0_0,y
	sta     _c_map,y
	iny
	cpy     #$F0
	bne     L08C0
;
; else
;
	rts
;
; memcpy(c_map2, level0_0, 240);
;
L08BA:	ldy     #$00
L08C6:	lda     _level0_0,y
	sta     _c_map2,y
	iny
	cpy     #$F0
	bne     L08C6
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ function_bank3 (void)
; ---------------------------------------------------------------

.segment	"BANK3"

.proc	_function_bank3: near

.segment	"BANK3"

;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ function_bank4 (void)
; ---------------------------------------------------------------

.segment	"BANK4"

.proc	_function_bank4: near

.segment	"BANK4"

;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ function_bank5 (void)
; ---------------------------------------------------------------

.segment	"BANK5"

.proc	_function_bank5: near

.segment	"BANK5"

;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ function_bank6 (void)
; ---------------------------------------------------------------

.segment	"BANK6"

.proc	_function_bank6: near

.segment	"BANK6"

;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; bank_spr(0);
;
	lda     #$00
	jsr     _bank_spr
;
; bank_bg(1);
;
	lda     #$01
	jsr     _bank_bg
;
; ppu_off();    // screen off
;
	jsr     _ppu_off
;
; pal_bg(palette_bg); // load the BG palette
;
	lda     #<(_palette_bg)
	ldx     #>(_palette_bg)
	jsr     _pal_bg
;
; pal_spr(palette_sp); // load the sprite palette
;
	lda     #<(_palette_sp)
	ldx     #>(_palette_sp)
	jsr     _pal_spr
;
; set_vram_buffer(); // do at least once
;
	jsr     _set_vram_buffer
;
; ppu_wait_nmi();
;
	jsr     _ppu_wait_nmi
;
; banked_call(BANK_2, bank2_load_room);  
;
	lda     #$02
	jsr     pusha
	lda     #<(_bank2_load_room)
	ldx     #>(_bank2_load_room)
	jsr     _banked_call
;
; ppu_on_all();   // turn on screen
;
	jsr     _ppu_on_all
;
; ppu_wait_nmi();     
;
L0907:	jsr     _ppu_wait_nmi
;
; pad1 = pad_poll(0);
;
	lda     #$00
	jsr     _pad_poll
	sta     _pad1
;
; pad1_new = get_pad_new(0); 
;
	lda     #$00
	jsr     _get_pad_new
	sta     _pad1_new
;
; if (pad1_new & PAD_START)    
;
	ldx     #$00
	and     #$10
	stx     tmp1
	ora     tmp1
;
; banked_call(BANK_0, bank0_player_movement);
;
	txa
	jsr     pusha
	lda     #<(_bank0_player_movement)
	ldx     #>(_bank0_player_movement)
	jsr     _banked_call
;
; oam_clear();  
;
	jsr     _oam_clear
;
; banked_call(BANK_0, bank0_draw_player_sprite);
;
	lda     #$00
	jsr     pusha
	lda     #<(_bank0_draw_player_sprite)
	ldx     #>(_bank0_draw_player_sprite)
	jsr     _banked_call
;
; while (1)      
;
	jmp     L0907

.endproc

